#pragma line 1 "cordic.cpp" ::: 0
#pragma line 1 "cordic.cpp" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 152 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot\\etc/autopilot_ssdm_op.h" 1 ::: 11
#pragma line 145 "C:/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 64
#pragma line 407 "C:/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 199
#pragma line 421 "C:/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 202
#pragma line 7 "<command line>" 2 ::: 204
#pragma line 1 "<built-in>" 2 ::: 205
#pragma line 1 "cordic.cpp" 2 ::: 206
#pragma line 1 "./cordic.h" 1 ::: 207
#pragma line 2 "cordic.cpp" 2 ::: 215
