-- ==============================================================
-- File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2016.2
-- Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
-- 
-- ==============================================================

library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity coshsinh_cordic_angles_neg_rom is 
    generic(
             dwidth     : integer := 64; 
             awidth     : integer := 4; 
             mem_size    : integer := 11
    ); 
    port (
          addr0      : in std_logic_vector(awidth-1 downto 0); 
          ce0       : in std_logic; 
          q0         : out std_logic_vector(dwidth-1 downto 0);
          clk       : in std_logic
    ); 
end entity; 


architecture rtl of coshsinh_cordic_angles_neg_rom is 

signal addr0_tmp : std_logic_vector(awidth-1 downto 0); 
type mem_array is array (0 to mem_size-1) of std_logic_vector (dwidth-1 downto 0); 
signal mem : mem_array := (
    0 => "0011111111101111001000101101000011100101011000000100000110001001", 
    1 => "0011111111110101101010011111101111100111011011001000101101000100", 
    2 => "0011111111111011011110001101010011111101111100111011011001000110", 
    3 => "0100000000000000100100101010001100000101010100110010011000011000", 
    4 => "0100000000000011011000000111010111110110111111010010000111111111", 
    5 => "0100000000000110001010100011000001010101001100100110000101111100", 
    6 => "0100000000001000111100100001001011010111011100110001100011111100", 
    7 => "0100000000001011101110001011101011000111000100001100101100101001", 
    8 => "0100000000001110011111110010111001001000111010001010011100011110", 
    9 => "0100000000010000101000101001110001110111100110100110101101010001", 
    10 => "0100000000010010000001011000011110010011110111011001011111110110" );

attribute syn_rom_style : string;
attribute syn_rom_style of mem : signal is "select_rom";
attribute ROM_STYLE : string;
attribute ROM_STYLE of mem : signal is "distributed";

attribute EQUIVALENT_REGISTER_REMOVAL : string;
begin 


memory_access_guard_0: process (addr0) 
begin
      addr0_tmp <= addr0;
--synthesis translate_off
      if (CONV_INTEGER(addr0) > mem_size-1) then
           addr0_tmp <= (others => '0');
      else 
           addr0_tmp <= addr0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
        if (ce0 = '1') then 
            q0 <= mem(CONV_INTEGER(addr0_tmp)); 
        end if;
    end if;
end process;

end rtl;


Library IEEE;
use IEEE.std_logic_1164.all;

entity coshsinh_cordic_angles_neg is
    generic (
        DataWidth : INTEGER := 64;
        AddressRange : INTEGER := 11;
        AddressWidth : INTEGER := 4);
    port (
        reset : IN STD_LOGIC;
        clk : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR(AddressWidth - 1 DOWNTO 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR(DataWidth - 1 DOWNTO 0));
end entity;

architecture arch of coshsinh_cordic_angles_neg is
    component coshsinh_cordic_angles_neg_rom is
        port (
            clk : IN STD_LOGIC;
            addr0 : IN STD_LOGIC_VECTOR;
            ce0 : IN STD_LOGIC;
            q0 : OUT STD_LOGIC_VECTOR);
    end component;



begin
    coshsinh_cordic_angles_neg_rom_U :  component coshsinh_cordic_angles_neg_rom
    port map (
        clk => clk,
        addr0 => address0,
        ce0 => ce0,
        q0 => q0);

end architecture;


