// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// ==============================================================

#include <systemc>
#include <iostream>
#include <cstdlib>
#include <cstddef>
#include <stdint.h>
#include "SysCFileHandler.h"
#include "ap_int.h"
#include "ap_fixed.h"
#include <complex>
#include <stdbool.h>
#include "autopilot_cbe.h"
#include "ap_stream.h"
#include "hls_stream.h"
#include "hls_half.h"
#include "hls_signal_handler.h"

using namespace std;
using namespace sc_core;
using namespace sc_dt;


// [dump_struct_tree [build_nameSpaceTree] dumpedStructList] ---------->


// [dump_enumeration [get_enumeration_list]] ---------->


// wrapc file define: "beta"
#define AUTOTB_TVIN_beta  "../tv/cdatafile/c.coshsinh_cordic.autotvin_beta.dat"
// wrapc file define: "m"
#define AUTOTB_TVIN_m  "../tv/cdatafile/c.coshsinh_cordic.autotvin_m.dat"
// wrapc file define: "n"
#define AUTOTB_TVIN_n  "../tv/cdatafile/c.coshsinh_cordic.autotvin_n.dat"
// wrapc file define: "ch"
#define AUTOTB_TVOUT_ch  "../tv/cdatafile/c.coshsinh_cordic.autotvout_ch.dat"
// wrapc file define: "sh"
#define AUTOTB_TVOUT_sh  "../tv/cdatafile/c.coshsinh_cordic.autotvout_sh.dat"

#define INTER_TCL  "../tv/cdatafile/ref.tcl"

// tvout file define: "ch"
#define AUTOTB_TVOUT_PC_ch  "../tv/rtldatafile/rtl.coshsinh_cordic.autotvout_ch.dat"
// tvout file define: "sh"
#define AUTOTB_TVOUT_PC_sh  "../tv/rtldatafile/rtl.coshsinh_cordic.autotvout_sh.dat"

class INTER_TCL_FILE {
	public:
		INTER_TCL_FILE(const char* name) {
			mName = name;
			beta_depth = 0;
			m_depth = 0;
			n_depth = 0;
			ch_depth = 0;
			sh_depth = 0;
			trans_num =0;
		}

		~INTER_TCL_FILE() {
			mFile.open(mName);
			if (!mFile.good()) {
				cout << "Failed to open file ref.tcl" << endl;
				exit (1);
			}
			string total_list = get_depth_list();
			mFile << "set depth_list {\n";
			mFile << total_list;
			mFile << "}\n";
			mFile << "set trans_num "<<trans_num<<endl;
			mFile.close();
		}

		string get_depth_list () {
			stringstream total_list;
			total_list << "{beta " << beta_depth << "}\n";
			total_list << "{m " << m_depth << "}\n";
			total_list << "{n " << n_depth << "}\n";
			total_list << "{ch " << ch_depth << "}\n";
			total_list << "{sh " << sh_depth << "}\n";
			return total_list.str();
		}

		void set_num (int num , int* class_num) {
			(*class_num) = (*class_num) > num ? (*class_num) : num;
		}
	public:
		int beta_depth;
		int m_depth;
		int n_depth;
		int ch_depth;
		int sh_depth;
		int trans_num;

	private:
		ofstream mFile;
		const char* mName;
};


#define coshsinh_cordic AESL_ORIG_DUT_coshsinh_cordic
extern void coshsinh_cordic (
double beta,
int m,
int n,
double* ch,
double* sh);
#undef coshsinh_cordic

void coshsinh_cordic (
double beta,
int m,
int n,
double* ch,
double* sh)
{
	refine_signal_handler();
	fstream wrapc_switch_file_token;
	wrapc_switch_file_token.open(".hls_cosim_wrapc_switch.log");
	int AESL_i;
	if (wrapc_switch_file_token.good())
	{
		CodeState = ENTER_WRAPC_PC;
		static unsigned AESL_transaction_pc = 0;
		string AESL_token;
		string AESL_num;
		static AESL_FILE_HANDLER aesl_fh;


		// output port post check: "ch"
		aesl_fh.read(AUTOTB_TVOUT_PC_ch, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_ch, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_ch, AESL_token); // data

			sc_bv<64> *ch_pc_buffer = new sc_bv<64>[1];
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'ch', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'ch', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					ch_pc_buffer[i] = AESL_token.c_str();
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_ch, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_ch))
				{
					exit(1);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: ch
				{
					// bitslice(63, 0)
					// {
						// celement: ch(63, 0)
						// {
							sc_lv<64>* ch_lv0_0_0_1 = new sc_lv<64>[1];
						// }
					// }

					// bitslice(63, 0)
					{
						int hls_map_index = 0;
						// celement: ch(63, 0)
						{
							// carray: (0) => (0) @ (1)
							for (int i_0 = 0; i_0 <= 0; i_0 += 1)
							{
								if (&(ch[0]) != NULL) // check the null address if the c port is array or others
								{
									ch_lv0_0_0_1[hls_map_index++].range(63, 0) = sc_bv<64>(ch_pc_buffer[hls_map_index].range(63, 0));
								}
							}
						}
					}

					// bitslice(63, 0)
					{
						int hls_map_index = 0;
						// celement: ch(63, 0)
						{
							// carray: (0) => (0) @ (1)
							for (int i_0 = 0; i_0 <= 0; i_0 += 1)
							{
								// sub                    : i_0
								// ori_name               : ch[i_0]
								// sub_1st_elem           : 0
								// ori_name_1st_elem      : ch[0]
								// output_left_conversion : *(long long*)&ch[i_0]
								// output_type_conversion : (ch_lv0_0_0_1[hls_map_index++]).to_uint64()
								if (&(ch[0]) != NULL) // check the null address if the c port is array or others
								{
									*(long long*)&ch[i_0] = (ch_lv0_0_0_1[hls_map_index++]).to_uint64();
								}
							}
						}
					}
				}
			}

			// release memory allocation
			delete [] ch_pc_buffer;
		}

		// output port post check: "sh"
		aesl_fh.read(AUTOTB_TVOUT_PC_sh, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_sh, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_sh, AESL_token); // data

			sc_bv<64> *sh_pc_buffer = new sc_bv<64>[1];
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'sh', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'sh', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					sh_pc_buffer[i] = AESL_token.c_str();
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_sh, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_sh))
				{
					exit(1);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: sh
				{
					// bitslice(63, 0)
					// {
						// celement: sh(63, 0)
						// {
							sc_lv<64>* sh_lv0_0_0_1 = new sc_lv<64>[1];
						// }
					// }

					// bitslice(63, 0)
					{
						int hls_map_index = 0;
						// celement: sh(63, 0)
						{
							// carray: (0) => (0) @ (1)
							for (int i_0 = 0; i_0 <= 0; i_0 += 1)
							{
								if (&(sh[0]) != NULL) // check the null address if the c port is array or others
								{
									sh_lv0_0_0_1[hls_map_index++].range(63, 0) = sc_bv<64>(sh_pc_buffer[hls_map_index].range(63, 0));
								}
							}
						}
					}

					// bitslice(63, 0)
					{
						int hls_map_index = 0;
						// celement: sh(63, 0)
						{
							// carray: (0) => (0) @ (1)
							for (int i_0 = 0; i_0 <= 0; i_0 += 1)
							{
								// sub                    : i_0
								// ori_name               : sh[i_0]
								// sub_1st_elem           : 0
								// ori_name_1st_elem      : sh[0]
								// output_left_conversion : *(long long*)&sh[i_0]
								// output_type_conversion : (sh_lv0_0_0_1[hls_map_index++]).to_uint64()
								if (&(sh[0]) != NULL) // check the null address if the c port is array or others
								{
									*(long long*)&sh[i_0] = (sh_lv0_0_0_1[hls_map_index++]).to_uint64();
								}
							}
						}
					}
				}
			}

			// release memory allocation
			delete [] sh_pc_buffer;
		}

		AESL_transaction_pc++;
	}
	else
	{
		CodeState = ENTER_WRAPC;
		static unsigned AESL_transaction;

		static AESL_FILE_HANDLER aesl_fh;

		// "beta"
		char* tvin_beta = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_beta);

		// "m"
		char* tvin_m = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_m);

		// "n"
		char* tvin_n = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_n);

		// "ch"
		char* tvout_ch = new char[50];
		aesl_fh.touch(AUTOTB_TVOUT_ch);

		// "sh"
		char* tvout_sh = new char[50];
		aesl_fh.touch(AUTOTB_TVOUT_sh);

		CodeState = DUMP_INPUTS;
		static INTER_TCL_FILE tcl_file(INTER_TCL);
		int leading_zero;

		// [[transaction]]
		sprintf(tvin_beta, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_beta, tvin_beta);

		sc_bv<64> beta_tvin_wrapc_buffer;

		// RTL Name: beta
		{
			// bitslice(63, 0)
			{
				// celement: beta(63, 0)
				{
					// carray: (0) => (0) @ (0)
					{
						// sub                   : 
						// ori_name              : beta
						// sub_1st_elem          : 
						// ori_name_1st_elem     : beta
						// regulate_c_name       : beta
						// input_type_conversion : *(long long*)&beta
						if (&(beta) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<64> beta_tmp_mem;
							beta_tmp_mem = *(long long*)&beta;
							beta_tvin_wrapc_buffer.range(63, 0) = beta_tmp_mem.range(63, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvin_beta, "%s\n", (beta_tvin_wrapc_buffer).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_beta, tvin_beta);
		}

		tcl_file.set_num(1, &tcl_file.beta_depth);
		sprintf(tvin_beta, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_beta, tvin_beta);

		// [[transaction]]
		sprintf(tvin_m, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_m, tvin_m);

		sc_bv<32> m_tvin_wrapc_buffer;

		// RTL Name: m
		{
			// bitslice(31, 0)
			{
				// celement: m(31, 0)
				{
					// carray: (0) => (0) @ (0)
					{
						// sub                   : 
						// ori_name              : m
						// sub_1st_elem          : 
						// ori_name_1st_elem     : m
						// regulate_c_name       : m
						// input_type_conversion : m
						if (&(m) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> m_tmp_mem;
							m_tmp_mem = m;
							m_tvin_wrapc_buffer.range(31, 0) = m_tmp_mem.range(31, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvin_m, "%s\n", (m_tvin_wrapc_buffer).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_m, tvin_m);
		}

		tcl_file.set_num(1, &tcl_file.m_depth);
		sprintf(tvin_m, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_m, tvin_m);

		// [[transaction]]
		sprintf(tvin_n, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_n, tvin_n);

		sc_bv<32> n_tvin_wrapc_buffer;

		// RTL Name: n
		{
			// bitslice(31, 0)
			{
				// celement: n(31, 0)
				{
					// carray: (0) => (0) @ (0)
					{
						// sub                   : 
						// ori_name              : n
						// sub_1st_elem          : 
						// ori_name_1st_elem     : n
						// regulate_c_name       : n
						// input_type_conversion : n
						if (&(n) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> n_tmp_mem;
							n_tmp_mem = n;
							n_tvin_wrapc_buffer.range(31, 0) = n_tmp_mem.range(31, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvin_n, "%s\n", (n_tvin_wrapc_buffer).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_n, tvin_n);
		}

		tcl_file.set_num(1, &tcl_file.n_depth);
		sprintf(tvin_n, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_n, tvin_n);

// [call_c_dut] ---------->

		CodeState = CALL_C_DUT;
		AESL_ORIG_DUT_coshsinh_cordic(beta, m, n, ch, sh);

		CodeState = DUMP_OUTPUTS;

		// [[transaction]]
		sprintf(tvout_ch, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_ch, tvout_ch);

		sc_bv<64>* ch_tvout_wrapc_buffer = new sc_bv<64>[1];

		// RTL Name: ch
		{
			// bitslice(63, 0)
			{
				int hls_map_index = 0;
				// celement: ch(63, 0)
				{
					// carray: (0) => (0) @ (1)
					for (int i_0 = 0; i_0 <= 0; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : ch[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : ch[0]
						// regulate_c_name       : ch
						// input_type_conversion : *(long long*)&ch[i_0]
						if (&(ch[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<64> ch_tmp_mem;
							ch_tmp_mem = *(long long*)&ch[i_0];
							ch_tvout_wrapc_buffer[hls_map_index++].range(63, 0) = ch_tmp_mem.range(63, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvout_ch, "%s\n", (ch_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_ch, tvout_ch);
		}

		tcl_file.set_num(1, &tcl_file.ch_depth);
		sprintf(tvout_ch, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_ch, tvout_ch);

		// release memory allocation
		delete [] ch_tvout_wrapc_buffer;

		// [[transaction]]
		sprintf(tvout_sh, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_sh, tvout_sh);

		sc_bv<64>* sh_tvout_wrapc_buffer = new sc_bv<64>[1];

		// RTL Name: sh
		{
			// bitslice(63, 0)
			{
				int hls_map_index = 0;
				// celement: sh(63, 0)
				{
					// carray: (0) => (0) @ (1)
					for (int i_0 = 0; i_0 <= 0; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : sh[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : sh[0]
						// regulate_c_name       : sh
						// input_type_conversion : *(long long*)&sh[i_0]
						if (&(sh[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<64> sh_tmp_mem;
							sh_tmp_mem = *(long long*)&sh[i_0];
							sh_tvout_wrapc_buffer[hls_map_index++].range(63, 0) = sh_tmp_mem.range(63, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvout_sh, "%s\n", (sh_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_sh, tvout_sh);
		}

		tcl_file.set_num(1, &tcl_file.sh_depth);
		sprintf(tvout_sh, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_sh, tvout_sh);

		// release memory allocation
		delete [] sh_tvout_wrapc_buffer;

		CodeState = DELETE_CHAR_BUFFERS;
		// release memory allocation: "beta"
		delete [] tvin_beta;
		// release memory allocation: "m"
		delete [] tvin_m;
		// release memory allocation: "n"
		delete [] tvin_n;
		// release memory allocation: "ch"
		delete [] tvout_ch;
		// release memory allocation: "sh"
		delete [] tvout_sh;

		AESL_transaction++;

		tcl_file.set_num(AESL_transaction , &tcl_file.trans_num);
	}
}

