// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "coshsinh_cordic.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic coshsinh_cordic::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic coshsinh_cordic::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<59> coshsinh_cordic::ap_ST_st1_fsm_0 = "1";
const sc_lv<59> coshsinh_cordic::ap_ST_st2_fsm_1 = "10";
const sc_lv<59> coshsinh_cordic::ap_ST_st3_fsm_2 = "100";
const sc_lv<59> coshsinh_cordic::ap_ST_st4_fsm_3 = "1000";
const sc_lv<59> coshsinh_cordic::ap_ST_st5_fsm_4 = "10000";
const sc_lv<59> coshsinh_cordic::ap_ST_st6_fsm_5 = "100000";
const sc_lv<59> coshsinh_cordic::ap_ST_st7_fsm_6 = "1000000";
const sc_lv<59> coshsinh_cordic::ap_ST_st8_fsm_7 = "10000000";
const sc_lv<59> coshsinh_cordic::ap_ST_st9_fsm_8 = "100000000";
const sc_lv<59> coshsinh_cordic::ap_ST_st10_fsm_9 = "1000000000";
const sc_lv<59> coshsinh_cordic::ap_ST_st11_fsm_10 = "10000000000";
const sc_lv<59> coshsinh_cordic::ap_ST_st12_fsm_11 = "100000000000";
const sc_lv<59> coshsinh_cordic::ap_ST_st13_fsm_12 = "1000000000000";
const sc_lv<59> coshsinh_cordic::ap_ST_st14_fsm_13 = "10000000000000";
const sc_lv<59> coshsinh_cordic::ap_ST_st15_fsm_14 = "100000000000000";
const sc_lv<59> coshsinh_cordic::ap_ST_st16_fsm_15 = "1000000000000000";
const sc_lv<59> coshsinh_cordic::ap_ST_st17_fsm_16 = "10000000000000000";
const sc_lv<59> coshsinh_cordic::ap_ST_st18_fsm_17 = "100000000000000000";
const sc_lv<59> coshsinh_cordic::ap_ST_st19_fsm_18 = "1000000000000000000";
const sc_lv<59> coshsinh_cordic::ap_ST_st20_fsm_19 = "10000000000000000000";
const sc_lv<59> coshsinh_cordic::ap_ST_st21_fsm_20 = "100000000000000000000";
const sc_lv<59> coshsinh_cordic::ap_ST_st22_fsm_21 = "1000000000000000000000";
const sc_lv<59> coshsinh_cordic::ap_ST_st23_fsm_22 = "10000000000000000000000";
const sc_lv<59> coshsinh_cordic::ap_ST_st24_fsm_23 = "100000000000000000000000";
const sc_lv<59> coshsinh_cordic::ap_ST_st25_fsm_24 = "1000000000000000000000000";
const sc_lv<59> coshsinh_cordic::ap_ST_st26_fsm_25 = "10000000000000000000000000";
const sc_lv<59> coshsinh_cordic::ap_ST_st27_fsm_26 = "100000000000000000000000000";
const sc_lv<59> coshsinh_cordic::ap_ST_st28_fsm_27 = "1000000000000000000000000000";
const sc_lv<59> coshsinh_cordic::ap_ST_st29_fsm_28 = "10000000000000000000000000000";
const sc_lv<59> coshsinh_cordic::ap_ST_st30_fsm_29 = "100000000000000000000000000000";
const sc_lv<59> coshsinh_cordic::ap_ST_st31_fsm_30 = "1000000000000000000000000000000";
const sc_lv<59> coshsinh_cordic::ap_ST_st32_fsm_31 = "10000000000000000000000000000000";
const sc_lv<59> coshsinh_cordic::ap_ST_st33_fsm_32 = "100000000000000000000000000000000";
const sc_lv<59> coshsinh_cordic::ap_ST_st34_fsm_33 = "1000000000000000000000000000000000";
const sc_lv<59> coshsinh_cordic::ap_ST_st35_fsm_34 = "10000000000000000000000000000000000";
const sc_lv<59> coshsinh_cordic::ap_ST_st36_fsm_35 = "100000000000000000000000000000000000";
const sc_lv<59> coshsinh_cordic::ap_ST_st37_fsm_36 = "1000000000000000000000000000000000000";
const sc_lv<59> coshsinh_cordic::ap_ST_st38_fsm_37 = "10000000000000000000000000000000000000";
const sc_lv<59> coshsinh_cordic::ap_ST_st39_fsm_38 = "100000000000000000000000000000000000000";
const sc_lv<59> coshsinh_cordic::ap_ST_st40_fsm_39 = "1000000000000000000000000000000000000000";
const sc_lv<59> coshsinh_cordic::ap_ST_st41_fsm_40 = "10000000000000000000000000000000000000000";
const sc_lv<59> coshsinh_cordic::ap_ST_st42_fsm_41 = "100000000000000000000000000000000000000000";
const sc_lv<59> coshsinh_cordic::ap_ST_st43_fsm_42 = "1000000000000000000000000000000000000000000";
const sc_lv<59> coshsinh_cordic::ap_ST_st44_fsm_43 = "10000000000000000000000000000000000000000000";
const sc_lv<59> coshsinh_cordic::ap_ST_st45_fsm_44 = "100000000000000000000000000000000000000000000";
const sc_lv<59> coshsinh_cordic::ap_ST_st46_fsm_45 = "1000000000000000000000000000000000000000000000";
const sc_lv<59> coshsinh_cordic::ap_ST_st47_fsm_46 = "10000000000000000000000000000000000000000000000";
const sc_lv<59> coshsinh_cordic::ap_ST_st48_fsm_47 = "100000000000000000000000000000000000000000000000";
const sc_lv<59> coshsinh_cordic::ap_ST_st49_fsm_48 = "1000000000000000000000000000000000000000000000000";
const sc_lv<59> coshsinh_cordic::ap_ST_st50_fsm_49 = "10000000000000000000000000000000000000000000000000";
const sc_lv<59> coshsinh_cordic::ap_ST_st51_fsm_50 = "100000000000000000000000000000000000000000000000000";
const sc_lv<59> coshsinh_cordic::ap_ST_st52_fsm_51 = "1000000000000000000000000000000000000000000000000000";
const sc_lv<59> coshsinh_cordic::ap_ST_st53_fsm_52 = "10000000000000000000000000000000000000000000000000000";
const sc_lv<59> coshsinh_cordic::ap_ST_st54_fsm_53 = "100000000000000000000000000000000000000000000000000000";
const sc_lv<59> coshsinh_cordic::ap_ST_st55_fsm_54 = "1000000000000000000000000000000000000000000000000000000";
const sc_lv<59> coshsinh_cordic::ap_ST_st56_fsm_55 = "10000000000000000000000000000000000000000000000000000000";
const sc_lv<59> coshsinh_cordic::ap_ST_st57_fsm_56 = "100000000000000000000000000000000000000000000000000000000";
const sc_lv<59> coshsinh_cordic::ap_ST_st58_fsm_57 = "1000000000000000000000000000000000000000000000000000000000";
const sc_lv<59> coshsinh_cordic::ap_ST_st59_fsm_58 = "10000000000000000000000000000000000000000000000000000000000";
const sc_lv<32> coshsinh_cordic::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> coshsinh_cordic::ap_const_lv1_1 = "1";
const sc_lv<32> coshsinh_cordic::ap_const_lv32_5 = "101";
const sc_lv<32> coshsinh_cordic::ap_const_lv32_D = "1101";
const sc_lv<32> coshsinh_cordic::ap_const_lv32_22 = "100010";
const sc_lv<32> coshsinh_cordic::ap_const_lv32_34 = "110100";
const sc_lv<1> coshsinh_cordic::ap_const_lv1_0 = "0";
const sc_lv<32> coshsinh_cordic::ap_const_lv32_7 = "111";
const sc_lv<32> coshsinh_cordic::ap_const_lv32_1D = "11101";
const sc_lv<32> coshsinh_cordic::ap_const_lv32_23 = "100011";
const sc_lv<32> coshsinh_cordic::ap_const_lv32_29 = "101001";
const sc_lv<32> coshsinh_cordic::ap_const_lv32_2F = "101111";
const sc_lv<32> coshsinh_cordic::ap_const_lv32_8 = "1000";
const sc_lv<32> coshsinh_cordic::ap_const_lv32_11 = "10001";
const sc_lv<32> coshsinh_cordic::ap_const_lv32_16 = "10110";
const sc_lv<32> coshsinh_cordic::ap_const_lv32_28 = "101000";
const sc_lv<32> coshsinh_cordic::ap_const_lv32_1 = "1";
const sc_lv<32> coshsinh_cordic::ap_const_lv32_2 = "10";
const sc_lv<32> coshsinh_cordic::ap_const_lv32_B = "1011";
const sc_lv<32> coshsinh_cordic::ap_const_lv32_17 = "10111";
const sc_lv<32> coshsinh_cordic::ap_const_lv32_1E = "11110";
const sc_lv<32> coshsinh_cordic::ap_const_lv32_2E = "101110";
const sc_lv<32> coshsinh_cordic::ap_const_lv32_35 = "110101";
const sc_lv<64> coshsinh_cordic::ap_const_lv64_3FF0000000000000 = "11111111110000000000000000000000000000000000000000000000000000";
const sc_lv<64> coshsinh_cordic::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<64> coshsinh_cordic::ap_const_lv64_3FB0000000000000 = "11111110110000000000000000000000000000000000000000000000000000";
const sc_lv<64> coshsinh_cordic::ap_const_lv64_3FE193DD97F62B6B = "11111111100001100100111101110110010111111101100010101101101011";
const sc_lv<32> coshsinh_cordic::ap_const_lv32_3A = "111010";
const sc_lv<32> coshsinh_cordic::ap_const_lv32_9 = "1001";
const sc_lv<32> coshsinh_cordic::ap_const_lv32_12 = "10010";
const sc_lv<32> coshsinh_cordic::ap_const_lv32_24 = "100100";
const sc_lv<32> coshsinh_cordic::ap_const_lv32_2A = "101010";
const sc_lv<32> coshsinh_cordic::ap_const_lv32_30 = "110000";
const sc_lv<64> coshsinh_cordic::ap_const_lv64_4000000000000000 = "100000000000000000000000000000000000000000000000000000000000000";
const sc_lv<32> coshsinh_cordic::ap_const_lv32_3 = "11";
const sc_lv<32> coshsinh_cordic::ap_const_lv32_6 = "110";
const sc_lv<32> coshsinh_cordic::ap_const_lv32_C = "1100";
const sc_lv<32> coshsinh_cordic::ap_const_lv32_18 = "11000";
const sc_lv<64> coshsinh_cordic::ap_const_lv64_3FE0000000000000 = "11111111100000000000000000000000000000000000000000000000000000";
const sc_lv<32> coshsinh_cordic::ap_const_lv32_3E = "111110";
const sc_lv<11> coshsinh_cordic::ap_const_lv11_7FF = "11111111111";
const sc_lv<52> coshsinh_cordic::ap_const_lv52_0 = "0000000000000000000000000000000000000000000000000000";
const sc_lv<64> coshsinh_cordic::ap_const_lv64_BFF0000000000000 = "1011111111110000000000000000000000000000000000000000000000000000";
const sc_lv<32> coshsinh_cordic::ap_const_lv32_3C = "111100";
const sc_lv<32> coshsinh_cordic::ap_const_lv32_4 = "100";
const sc_lv<2> coshsinh_cordic::ap_const_lv2_0 = "00";
const sc_lv<2> coshsinh_cordic::ap_const_lv2_1 = "1";
const sc_lv<5> coshsinh_cordic::ap_const_lv5_4 = "100";

coshsinh_cordic::coshsinh_cordic(sc_module_name name) : sc_module(name), mVcdFile(0) {
    angles_neg_U = new coshsinh_cordic_angles_neg("angles_neg_U");
    angles_neg_U->clk(ap_clk);
    angles_neg_U->reset(ap_rst);
    angles_neg_U->address0(angles_neg_address0);
    angles_neg_U->ce0(angles_neg_ce0);
    angles_neg_U->q0(angles_neg_q0);
    angles_pos_U = new coshsinh_cordic_angles_pos("angles_pos_U");
    angles_pos_U->clk(ap_clk);
    angles_pos_U->reset(ap_rst);
    angles_pos_U->address0(angles_pos_address0);
    angles_pos_U->ce0(angles_pos_ce0);
    angles_pos_U->q0(angles_pos_q0);
    coshsinh_cordic_dadddsub_64ns_64ns_64_5_full_dsp_U0 = new coshsinh_cordic_dadddsub_64ns_64ns_64_5_full_dsp<1,5,64,64,64>("coshsinh_cordic_dadddsub_64ns_64ns_64_5_full_dsp_U0");
    coshsinh_cordic_dadddsub_64ns_64ns_64_5_full_dsp_U0->clk(ap_clk);
    coshsinh_cordic_dadddsub_64ns_64ns_64_5_full_dsp_U0->reset(ap_rst);
    coshsinh_cordic_dadddsub_64ns_64ns_64_5_full_dsp_U0->din0(grp_fu_243_p0);
    coshsinh_cordic_dadddsub_64ns_64ns_64_5_full_dsp_U0->din1(grp_fu_243_p1);
    coshsinh_cordic_dadddsub_64ns_64ns_64_5_full_dsp_U0->opcode(grp_fu_243_opcode);
    coshsinh_cordic_dadddsub_64ns_64ns_64_5_full_dsp_U0->ce(ap_var_for_const0);
    coshsinh_cordic_dadddsub_64ns_64ns_64_5_full_dsp_U0->dout(grp_fu_243_p2);
    coshsinh_cordic_dadd_64ns_64ns_64_5_full_dsp_U1 = new coshsinh_cordic_dadd_64ns_64ns_64_5_full_dsp<1,5,64,64,64>("coshsinh_cordic_dadd_64ns_64ns_64_5_full_dsp_U1");
    coshsinh_cordic_dadd_64ns_64ns_64_5_full_dsp_U1->clk(ap_clk);
    coshsinh_cordic_dadd_64ns_64ns_64_5_full_dsp_U1->reset(ap_rst);
    coshsinh_cordic_dadd_64ns_64ns_64_5_full_dsp_U1->din0(reg_315);
    coshsinh_cordic_dadd_64ns_64ns_64_5_full_dsp_U1->din1(grp_fu_251_p1);
    coshsinh_cordic_dadd_64ns_64ns_64_5_full_dsp_U1->ce(ap_var_for_const0);
    coshsinh_cordic_dadd_64ns_64ns_64_5_full_dsp_U1->dout(grp_fu_251_p2);
    coshsinh_cordic_dmul_64ns_64ns_64_6_max_dsp_U2 = new coshsinh_cordic_dmul_64ns_64ns_64_6_max_dsp<1,6,64,64,64>("coshsinh_cordic_dmul_64ns_64ns_64_6_max_dsp_U2");
    coshsinh_cordic_dmul_64ns_64ns_64_6_max_dsp_U2->clk(ap_clk);
    coshsinh_cordic_dmul_64ns_64ns_64_6_max_dsp_U2->reset(ap_rst);
    coshsinh_cordic_dmul_64ns_64ns_64_6_max_dsp_U2->din0(grp_fu_259_p0);
    coshsinh_cordic_dmul_64ns_64ns_64_6_max_dsp_U2->din1(grp_fu_259_p1);
    coshsinh_cordic_dmul_64ns_64ns_64_6_max_dsp_U2->ce(ap_var_for_const0);
    coshsinh_cordic_dmul_64ns_64ns_64_6_max_dsp_U2->dout(grp_fu_259_p2);
    coshsinh_cordic_dmul_64ns_64ns_64_6_max_dsp_U3 = new coshsinh_cordic_dmul_64ns_64ns_64_6_max_dsp<1,6,64,64,64>("coshsinh_cordic_dmul_64ns_64ns_64_6_max_dsp_U3");
    coshsinh_cordic_dmul_64ns_64ns_64_6_max_dsp_U3->clk(ap_clk);
    coshsinh_cordic_dmul_64ns_64ns_64_6_max_dsp_U3->reset(ap_rst);
    coshsinh_cordic_dmul_64ns_64ns_64_6_max_dsp_U3->din0(grp_fu_266_p0);
    coshsinh_cordic_dmul_64ns_64ns_64_6_max_dsp_U3->din1(grp_fu_266_p1);
    coshsinh_cordic_dmul_64ns_64ns_64_6_max_dsp_U3->ce(ap_var_for_const0);
    coshsinh_cordic_dmul_64ns_64ns_64_6_max_dsp_U3->dout(grp_fu_266_p2);
    coshsinh_cordic_dmul_64ns_64ns_64_6_max_dsp_U4 = new coshsinh_cordic_dmul_64ns_64ns_64_6_max_dsp<1,6,64,64,64>("coshsinh_cordic_dmul_64ns_64ns_64_6_max_dsp_U4");
    coshsinh_cordic_dmul_64ns_64ns_64_6_max_dsp_U4->clk(ap_clk);
    coshsinh_cordic_dmul_64ns_64ns_64_6_max_dsp_U4->reset(ap_rst);
    coshsinh_cordic_dmul_64ns_64ns_64_6_max_dsp_U4->din0(grp_fu_277_p0);
    coshsinh_cordic_dmul_64ns_64ns_64_6_max_dsp_U4->din1(ap_var_for_const1);
    coshsinh_cordic_dmul_64ns_64ns_64_6_max_dsp_U4->ce(ap_var_for_const0);
    coshsinh_cordic_dmul_64ns_64ns_64_6_max_dsp_U4->dout(grp_fu_277_p2);
    coshsinh_cordic_dcmp_64ns_64ns_1_1_U5 = new coshsinh_cordic_dcmp_64ns_64ns_1_1<1,1,64,64,1>("coshsinh_cordic_dcmp_64ns_64ns_1_1_U5");
    coshsinh_cordic_dcmp_64ns_64ns_1_1_U5->din0(grp_fu_286_p0);
    coshsinh_cordic_dcmp_64ns_64ns_1_1_U5->din1(ap_var_for_const2);
    coshsinh_cordic_dcmp_64ns_64ns_1_1_U5->opcode(ap_var_for_const3);
    coshsinh_cordic_dcmp_64ns_64ns_1_1_U5->dout(grp_fu_286_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_angle_3_fu_571_p3);
    sensitive << ( angles_pos_q0 );
    sensitive << ( reg_335 );
    sensitive << ( tmp_21_reg_711 );

    SC_METHOD(thread_angles_neg_address0);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( tmp_5_fu_408_p1 );

    SC_METHOD(thread_angles_neg_ce0);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_angles_pos_address0);
    sensitive << ( ap_sig_cseq_ST_st30_fsm_29 );
    sensitive << ( tmp_22_fu_566_p1 );

    SC_METHOD(thread_angles_pos_ce0);
    sensitive << ( ap_sig_cseq_ST_st30_fsm_29 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_sig_cseq_ST_st59_fsm_58 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_cseq_ST_st59_fsm_58 );

    SC_METHOD(thread_ap_sig_109);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_116);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_124);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_132);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_147);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_154);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_162);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_170);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_178);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_188);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_195);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_211);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_218);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_248);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_262);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_272);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_281);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_300);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_310);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_323);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_362);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_371);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_378);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_385);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_392);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_399);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_416);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_423);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_431);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_438);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_74);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_st10_fsm_9);
    sensitive << ( ap_sig_371 );

    SC_METHOD(thread_ap_sig_cseq_ST_st12_fsm_11);
    sensitive << ( ap_sig_272 );

    SC_METHOD(thread_ap_sig_cseq_ST_st13_fsm_12);
    sensitive << ( ap_sig_431 );

    SC_METHOD(thread_ap_sig_cseq_ST_st14_fsm_13);
    sensitive << ( ap_sig_116 );

    SC_METHOD(thread_ap_sig_cseq_ST_st18_fsm_17);
    sensitive << ( ap_sig_195 );

    SC_METHOD(thread_ap_sig_cseq_ST_st19_fsm_18);
    sensitive << ( ap_sig_378 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_74 );

    SC_METHOD(thread_ap_sig_cseq_ST_st23_fsm_22);
    sensitive << ( ap_sig_211 );

    SC_METHOD(thread_ap_sig_cseq_ST_st24_fsm_23);
    sensitive << ( ap_sig_281 );

    SC_METHOD(thread_ap_sig_cseq_ST_st25_fsm_24);
    sensitive << ( ap_sig_438 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_248 );

    SC_METHOD(thread_ap_sig_cseq_ST_st30_fsm_29);
    sensitive << ( ap_sig_154 );

    SC_METHOD(thread_ap_sig_cseq_ST_st31_fsm_30);
    sensitive << ( ap_sig_300 );

    SC_METHOD(thread_ap_sig_cseq_ST_st35_fsm_34);
    sensitive << ( ap_sig_124 );

    SC_METHOD(thread_ap_sig_cseq_ST_st36_fsm_35);
    sensitive << ( ap_sig_162 );

    SC_METHOD(thread_ap_sig_cseq_ST_st37_fsm_36);
    sensitive << ( ap_sig_385 );

    SC_METHOD(thread_ap_sig_cseq_ST_st3_fsm_2);
    sensitive << ( ap_sig_262 );

    SC_METHOD(thread_ap_sig_cseq_ST_st41_fsm_40);
    sensitive << ( ap_sig_218 );

    SC_METHOD(thread_ap_sig_cseq_ST_st42_fsm_41);
    sensitive << ( ap_sig_170 );

    SC_METHOD(thread_ap_sig_cseq_ST_st43_fsm_42);
    sensitive << ( ap_sig_392 );

    SC_METHOD(thread_ap_sig_cseq_ST_st47_fsm_46);
    sensitive << ( ap_sig_310 );

    SC_METHOD(thread_ap_sig_cseq_ST_st48_fsm_47);
    sensitive << ( ap_sig_178 );

    SC_METHOD(thread_ap_sig_cseq_ST_st49_fsm_48);
    sensitive << ( ap_sig_399 );

    SC_METHOD(thread_ap_sig_cseq_ST_st4_fsm_3);
    sensitive << ( ap_sig_416 );

    SC_METHOD(thread_ap_sig_cseq_ST_st53_fsm_52);
    sensitive << ( ap_sig_132 );

    SC_METHOD(thread_ap_sig_cseq_ST_st54_fsm_53);
    sensitive << ( ap_sig_323 );

    SC_METHOD(thread_ap_sig_cseq_ST_st59_fsm_58);
    sensitive << ( ap_sig_362 );

    SC_METHOD(thread_ap_sig_cseq_ST_st6_fsm_5);
    sensitive << ( ap_sig_109 );

    SC_METHOD(thread_ap_sig_cseq_ST_st7_fsm_6);
    sensitive << ( ap_sig_423 );

    SC_METHOD(thread_ap_sig_cseq_ST_st8_fsm_7);
    sensitive << ( ap_sig_147 );

    SC_METHOD(thread_ap_sig_cseq_ST_st9_fsm_8);
    sensitive << ( ap_sig_188 );

    SC_METHOD(thread_beta_assign_1_to_int_fu_578_p1);
    sensitive << ( reg_294 );

    SC_METHOD(thread_beta_assign_3_fu_628_p3);
    sensitive << ( reg_294 );
    sensitive << ( sel_tmp4_reg_716 );
    sensitive << ( beta_assign_2_reg_739 );

    SC_METHOD(thread_beta_to_int_fu_340_p1);
    sensitive << ( beta );

    SC_METHOD(thread_c2_3_fu_634_p3);
    sensitive << ( reg_294 );
    sensitive << ( sel_tmp4_reg_716 );
    sensitive << ( reg_321 );

    SC_METHOD(thread_ch);
    sensitive << ( grp_fu_259_p2 );
    sensitive << ( ap_sig_cseq_ST_st59_fsm_58 );

    SC_METHOD(thread_ch_ap_vld);
    sensitive << ( ap_sig_cseq_ST_st59_fsm_58 );

    SC_METHOD(thread_grp_fu_243_opcode);
    sensitive << ( sel_tmp4_reg_716 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( tmp_3_fu_396_p2 );
    sensitive << ( ap_sig_cseq_ST_st31_fsm_30 );
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( ap_sig_cseq_ST_st19_fsm_18 );
    sensitive << ( ap_sig_cseq_ST_st37_fsm_36 );
    sensitive << ( ap_sig_cseq_ST_st43_fsm_42 );
    sensitive << ( ap_sig_cseq_ST_st49_fsm_48 );

    SC_METHOD(thread_grp_fu_243_p0);
    sensitive << ( reg_294 );
    sensitive << ( reg_321 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st31_fsm_30 );
    sensitive << ( ch_load_reg_120 );
    sensitive << ( p_0_reg_165 );
    sensitive << ( ch_load_2_reg_175 );
    sensitive << ( p_1_reg_232 );
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( ap_sig_cseq_ST_st19_fsm_18 );
    sensitive << ( ap_sig_cseq_ST_st37_fsm_36 );
    sensitive << ( ap_sig_cseq_ST_st43_fsm_42 );
    sensitive << ( ap_sig_cseq_ST_st49_fsm_48 );

    SC_METHOD(thread_grp_fu_243_p1);
    sensitive << ( reg_302 );
    sensitive << ( reg_310 );
    sensitive << ( reg_315 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st31_fsm_30 );
    sensitive << ( poweroftwo_reg_144 );
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( ap_sig_cseq_ST_st19_fsm_18 );
    sensitive << ( ap_sig_cseq_ST_st37_fsm_36 );
    sensitive << ( ap_sig_cseq_ST_st43_fsm_42 );
    sensitive << ( ap_sig_cseq_ST_st49_fsm_48 );

    SC_METHOD(thread_grp_fu_251_p1);
    sensitive << ( reg_328 );
    sensitive << ( tmp_2_reg_132 );
    sensitive << ( sh_load_reg_186 );
    sensitive << ( ap_sig_cseq_ST_st19_fsm_18 );
    sensitive << ( ap_sig_cseq_ST_st37_fsm_36 );
    sensitive << ( ap_sig_cseq_ST_st49_fsm_48 );

    SC_METHOD(thread_grp_fu_259_p0);
    sensitive << ( reg_302 );
    sensitive << ( sign_factor_reg_657 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( sigma_reg_686 );
    sensitive << ( factor_reg_691 );
    sensitive << ( sigma_1_reg_700 );
    sensitive << ( ap_sig_cseq_ST_st24_fsm_23 );
    sensitive << ( ap_sig_cseq_ST_st31_fsm_30 );
    sensitive << ( sigma_2_reg_733 );
    sensitive << ( poweroftwo_reg_144 );
    sensitive << ( ap_sig_cseq_ST_st37_fsm_36 );
    sensitive << ( ap_sig_cseq_ST_st43_fsm_42 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st13_fsm_12 );
    sensitive << ( ap_sig_cseq_ST_st25_fsm_24 );

    SC_METHOD(thread_grp_fu_259_p1);
    sensitive << ( reg_294 );
    sensitive << ( reg_328 );
    sensitive << ( angle_reg_681 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( ap_sig_cseq_ST_st24_fsm_23 );
    sensitive << ( ap_sig_cseq_ST_st31_fsm_30 );
    sensitive << ( tmp_2_reg_132 );
    sensitive << ( ch_load_2_reg_175 );
    sensitive << ( sh_load_reg_186 );
    sensitive << ( poweroftwo_1_reg_209 );
    sensitive << ( ap_sig_cseq_ST_st37_fsm_36 );
    sensitive << ( ap_sig_cseq_ST_st43_fsm_42 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st13_fsm_12 );
    sensitive << ( ap_sig_cseq_ST_st25_fsm_24 );

    SC_METHOD(thread_grp_fu_266_p0);
    sensitive << ( reg_302 );
    sensitive << ( sign_factor_reg_657 );
    sensitive << ( factor_reg_691 );
    sensitive << ( sigma_1_reg_700 );
    sensitive << ( ap_sig_cseq_ST_st24_fsm_23 );
    sensitive << ( ap_sig_cseq_ST_st31_fsm_30 );
    sensitive << ( sigma_2_reg_733 );
    sensitive << ( ap_sig_cseq_ST_st37_fsm_36 );
    sensitive << ( ap_sig_cseq_ST_st43_fsm_42 );
    sensitive << ( ap_sig_cseq_ST_st13_fsm_12 );
    sensitive << ( ap_sig_cseq_ST_st25_fsm_24 );

    SC_METHOD(thread_grp_fu_266_p1);
    sensitive << ( reg_321 );
    sensitive << ( ap_sig_cseq_ST_st24_fsm_23 );
    sensitive << ( ap_sig_cseq_ST_st31_fsm_30 );
    sensitive << ( ch_load_reg_120 );
    sensitive << ( ch_load_2_reg_175 );
    sensitive << ( sh_load_reg_186 );
    sensitive << ( angle1_reg_197 );
    sensitive << ( ap_sig_cseq_ST_st37_fsm_36 );
    sensitive << ( ap_sig_cseq_ST_st43_fsm_42 );
    sensitive << ( ap_sig_cseq_ST_st13_fsm_12 );
    sensitive << ( ap_sig_cseq_ST_st25_fsm_24 );

    SC_METHOD(thread_grp_fu_277_p0);
    sensitive << ( angle1_reg_197 );
    sensitive << ( poweroftwo_1_reg_209 );
    sensitive << ( ap_sig_cseq_ST_st37_fsm_36 );
    sensitive << ( ap_sig_cseq_ST_st25_fsm_24 );

    SC_METHOD(thread_grp_fu_286_p0);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( beta );
    sensitive << ( reg_294 );
    sensitive << ( ap_sig_cseq_ST_st36_fsm_35 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( ap_sig_cseq_ST_st24_fsm_23 );
    sensitive << ( p_0_reg_165 );
    sensitive << ( p_1_reg_232 );

    SC_METHOD(thread_j_2_fu_413_p2);
    sensitive << ( j1_reg_156 );

    SC_METHOD(thread_j_3_fu_524_p2);
    sensitive << ( j_1_reg_220 );

    SC_METHOD(thread_j_fu_390_p2);
    sensitive << ( m );

    SC_METHOD(thread_notlhs1_fu_437_p2);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( tmp_23_fu_423_p4 );

    SC_METHOD(thread_notlhs2_fu_492_p2);
    sensitive << ( ap_sig_cseq_ST_st24_fsm_23 );
    sensitive << ( tmp_8_fu_469_p2 );
    sensitive << ( tmp_28_fu_478_p4 );

    SC_METHOD(thread_notlhs3_fu_596_p2);
    sensitive << ( ap_sig_cseq_ST_st36_fsm_35 );
    sensitive << ( tmp_33_fu_582_p4 );

    SC_METHOD(thread_notlhs_fu_358_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( tmp_fu_344_p4 );

    SC_METHOD(thread_notrhs1_fu_443_p2);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( tmp_24_fu_433_p1 );

    SC_METHOD(thread_notrhs2_fu_498_p2);
    sensitive << ( ap_sig_cseq_ST_st24_fsm_23 );
    sensitive << ( tmp_8_fu_469_p2 );
    sensitive << ( tmp_29_fu_488_p1 );

    SC_METHOD(thread_notrhs3_fu_602_p2);
    sensitive << ( ap_sig_cseq_ST_st36_fsm_35 );
    sensitive << ( tmp_34_fu_592_p1 );

    SC_METHOD(thread_notrhs_fu_364_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( tmp_6_fu_354_p1 );

    SC_METHOD(thread_p_0_to_int_fu_419_p1);
    sensitive << ( p_0_reg_165 );

    SC_METHOD(thread_p_1_to_int_fu_474_p1);
    sensitive << ( p_1_reg_232 );

    SC_METHOD(thread_s2_3_fu_641_p3);
    sensitive << ( sel_tmp4_reg_716 );
    sensitive << ( reg_328 );
    sensitive << ( s2_2_reg_749 );

    SC_METHOD(thread_sel_tmp1_fu_542_p2);
    sensitive << ( ap_sig_cseq_ST_st30_fsm_29 );
    sensitive << ( j_1_reg_220 );

    SC_METHOD(thread_sel_tmp2_fu_548_p2);
    sensitive << ( ap_sig_cseq_ST_st30_fsm_29 );
    sensitive << ( j_1_reg_220 );

    SC_METHOD(thread_sel_tmp4_fu_560_p2);
    sensitive << ( tmp1_fu_554_p2 );
    sensitive << ( sel_tmp_fu_536_p2 );

    SC_METHOD(thread_sel_tmp_fu_536_p2);
    sensitive << ( ap_sig_cseq_ST_st30_fsm_29 );
    sensitive << ( j_1_reg_220 );

    SC_METHOD(thread_sh);
    sensitive << ( grp_fu_266_p2 );
    sensitive << ( ap_sig_cseq_ST_st59_fsm_58 );

    SC_METHOD(thread_sh_ap_vld);
    sensitive << ( ap_sig_cseq_ST_st59_fsm_58 );

    SC_METHOD(thread_sigma_1_fu_516_p3);
    sensitive << ( tmp_32_fu_510_p2 );

    SC_METHOD(thread_sigma_2_fu_620_p3);
    sensitive << ( tmp_37_fu_614_p2 );

    SC_METHOD(thread_sigma_fu_461_p3);
    sensitive << ( tmp_27_fu_455_p2 );

    SC_METHOD(thread_sign_factor_fu_382_p3);
    sensitive << ( tmp_20_fu_376_p2 );

    SC_METHOD(thread_tmp1_fu_554_p2);
    sensitive << ( sel_tmp1_fu_542_p2 );
    sensitive << ( sel_tmp2_fu_548_p2 );

    SC_METHOD(thread_tmp_12_fu_370_p2);
    sensitive << ( notrhs_fu_364_p2 );
    sensitive << ( notlhs_fu_358_p2 );

    SC_METHOD(thread_tmp_20_fu_376_p2);
    sensitive << ( tmp_12_fu_370_p2 );
    sensitive << ( grp_fu_286_p2 );

    SC_METHOD(thread_tmp_21_fu_530_p2);
    sensitive << ( ap_sig_cseq_ST_st24_fsm_23 );
    sensitive << ( tmp_8_fu_469_p2 );
    sensitive << ( j_3_fu_524_p2 );

    SC_METHOD(thread_tmp_22_fu_566_p1);
    sensitive << ( j_1_reg_220 );

    SC_METHOD(thread_tmp_23_fu_423_p4);
    sensitive << ( p_0_to_int_fu_419_p1 );

    SC_METHOD(thread_tmp_24_fu_433_p1);
    sensitive << ( p_0_to_int_fu_419_p1 );

    SC_METHOD(thread_tmp_25_fu_449_p2);
    sensitive << ( notrhs1_fu_443_p2 );
    sensitive << ( notlhs1_fu_437_p2 );

    SC_METHOD(thread_tmp_27_fu_455_p2);
    sensitive << ( grp_fu_286_p2 );
    sensitive << ( tmp_25_fu_449_p2 );

    SC_METHOD(thread_tmp_28_fu_478_p4);
    sensitive << ( p_1_to_int_fu_474_p1 );

    SC_METHOD(thread_tmp_29_fu_488_p1);
    sensitive << ( p_1_to_int_fu_474_p1 );

    SC_METHOD(thread_tmp_30_fu_504_p2);
    sensitive << ( notrhs2_fu_498_p2 );
    sensitive << ( notlhs2_fu_492_p2 );

    SC_METHOD(thread_tmp_32_fu_510_p2);
    sensitive << ( grp_fu_286_p2 );
    sensitive << ( tmp_30_fu_504_p2 );

    SC_METHOD(thread_tmp_33_fu_582_p4);
    sensitive << ( beta_assign_1_to_int_fu_578_p1 );

    SC_METHOD(thread_tmp_34_fu_592_p1);
    sensitive << ( beta_assign_1_to_int_fu_578_p1 );

    SC_METHOD(thread_tmp_35_fu_608_p2);
    sensitive << ( notrhs3_fu_602_p2 );
    sensitive << ( notlhs3_fu_596_p2 );

    SC_METHOD(thread_tmp_37_fu_614_p2);
    sensitive << ( grp_fu_286_p2 );
    sensitive << ( tmp_35_fu_608_p2 );

    SC_METHOD(thread_tmp_3_fu_396_p2);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( j1_reg_156 );

    SC_METHOD(thread_tmp_4_fu_402_p2);
    sensitive << ( j1_reg_156 );

    SC_METHOD(thread_tmp_5_fu_408_p1);
    sensitive << ( tmp_4_fu_402_p2 );

    SC_METHOD(thread_tmp_6_fu_354_p1);
    sensitive << ( beta_to_int_fu_340_p1 );

    SC_METHOD(thread_tmp_8_fu_469_p2);
    sensitive << ( n );
    sensitive << ( ap_sig_cseq_ST_st24_fsm_23 );
    sensitive << ( j_1_reg_220 );

    SC_METHOD(thread_tmp_fu_344_p4);
    sensitive << ( beta_to_int_fu_340_p1 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_3_fu_396_p2 );
    sensitive << ( tmp_8_fu_469_p2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    SC_THREAD(thread_ap_var_for_const2);

    SC_THREAD(thread_ap_var_for_const1);

    SC_THREAD(thread_ap_var_for_const3);

    ap_CS_fsm = "00000000000000000000000000000000000000000000000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "coshsinh_cordic_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, beta, "(port)beta");
    sc_trace(mVcdFile, m, "(port)m");
    sc_trace(mVcdFile, n, "(port)n");
    sc_trace(mVcdFile, ch, "(port)ch");
    sc_trace(mVcdFile, ch_ap_vld, "(port)ch_ap_vld");
    sc_trace(mVcdFile, sh, "(port)sh");
    sc_trace(mVcdFile, sh_ap_vld, "(port)sh_ap_vld");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_74, "ap_sig_74");
    sc_trace(mVcdFile, angles_neg_address0, "angles_neg_address0");
    sc_trace(mVcdFile, angles_neg_ce0, "angles_neg_ce0");
    sc_trace(mVcdFile, angles_neg_q0, "angles_neg_q0");
    sc_trace(mVcdFile, angles_pos_address0, "angles_pos_address0");
    sc_trace(mVcdFile, angles_pos_ce0, "angles_pos_ce0");
    sc_trace(mVcdFile, angles_pos_q0, "angles_pos_q0");
    sc_trace(mVcdFile, grp_fu_243_p2, "grp_fu_243_p2");
    sc_trace(mVcdFile, reg_294, "reg_294");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st6_fsm_5, "ap_sig_cseq_ST_st6_fsm_5");
    sc_trace(mVcdFile, ap_sig_109, "ap_sig_109");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st14_fsm_13, "ap_sig_cseq_ST_st14_fsm_13");
    sc_trace(mVcdFile, ap_sig_116, "ap_sig_116");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st35_fsm_34, "ap_sig_cseq_ST_st35_fsm_34");
    sc_trace(mVcdFile, ap_sig_124, "ap_sig_124");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st53_fsm_52, "ap_sig_cseq_ST_st53_fsm_52");
    sc_trace(mVcdFile, ap_sig_132, "ap_sig_132");
    sc_trace(mVcdFile, sel_tmp4_reg_716, "sel_tmp4_reg_716");
    sc_trace(mVcdFile, grp_fu_259_p2, "grp_fu_259_p2");
    sc_trace(mVcdFile, reg_302, "reg_302");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st8_fsm_7, "ap_sig_cseq_ST_st8_fsm_7");
    sc_trace(mVcdFile, ap_sig_147, "ap_sig_147");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st30_fsm_29, "ap_sig_cseq_ST_st30_fsm_29");
    sc_trace(mVcdFile, ap_sig_154, "ap_sig_154");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st36_fsm_35, "ap_sig_cseq_ST_st36_fsm_35");
    sc_trace(mVcdFile, ap_sig_162, "ap_sig_162");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st42_fsm_41, "ap_sig_cseq_ST_st42_fsm_41");
    sc_trace(mVcdFile, ap_sig_170, "ap_sig_170");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st48_fsm_47, "ap_sig_cseq_ST_st48_fsm_47");
    sc_trace(mVcdFile, ap_sig_178, "ap_sig_178");
    sc_trace(mVcdFile, reg_310, "reg_310");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st9_fsm_8, "ap_sig_cseq_ST_st9_fsm_8");
    sc_trace(mVcdFile, ap_sig_188, "ap_sig_188");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st18_fsm_17, "ap_sig_cseq_ST_st18_fsm_17");
    sc_trace(mVcdFile, ap_sig_195, "ap_sig_195");
    sc_trace(mVcdFile, grp_fu_266_p2, "grp_fu_266_p2");
    sc_trace(mVcdFile, reg_315, "reg_315");
    sc_trace(mVcdFile, reg_321, "reg_321");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st23_fsm_22, "ap_sig_cseq_ST_st23_fsm_22");
    sc_trace(mVcdFile, ap_sig_211, "ap_sig_211");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st41_fsm_40, "ap_sig_cseq_ST_st41_fsm_40");
    sc_trace(mVcdFile, ap_sig_218, "ap_sig_218");
    sc_trace(mVcdFile, grp_fu_251_p2, "grp_fu_251_p2");
    sc_trace(mVcdFile, reg_328, "reg_328");
    sc_trace(mVcdFile, grp_fu_277_p2, "grp_fu_277_p2");
    sc_trace(mVcdFile, reg_335, "reg_335");
    sc_trace(mVcdFile, tmp_21_reg_711, "tmp_21_reg_711");
    sc_trace(mVcdFile, sign_factor_fu_382_p3, "sign_factor_fu_382_p3");
    sc_trace(mVcdFile, sign_factor_reg_657, "sign_factor_reg_657");
    sc_trace(mVcdFile, j_fu_390_p2, "j_fu_390_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_248, "ap_sig_248");
    sc_trace(mVcdFile, tmp_3_fu_396_p2, "tmp_3_fu_396_p2");
    sc_trace(mVcdFile, j_2_fu_413_p2, "j_2_fu_413_p2");
    sc_trace(mVcdFile, j_2_reg_676, "j_2_reg_676");
    sc_trace(mVcdFile, angle_reg_681, "angle_reg_681");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st3_fsm_2, "ap_sig_cseq_ST_st3_fsm_2");
    sc_trace(mVcdFile, ap_sig_262, "ap_sig_262");
    sc_trace(mVcdFile, sigma_fu_461_p3, "sigma_fu_461_p3");
    sc_trace(mVcdFile, sigma_reg_686, "sigma_reg_686");
    sc_trace(mVcdFile, factor_reg_691, "factor_reg_691");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st12_fsm_11, "ap_sig_cseq_ST_st12_fsm_11");
    sc_trace(mVcdFile, ap_sig_272, "ap_sig_272");
    sc_trace(mVcdFile, sigma_1_fu_516_p3, "sigma_1_fu_516_p3");
    sc_trace(mVcdFile, sigma_1_reg_700, "sigma_1_reg_700");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st24_fsm_23, "ap_sig_cseq_ST_st24_fsm_23");
    sc_trace(mVcdFile, ap_sig_281, "ap_sig_281");
    sc_trace(mVcdFile, tmp_8_fu_469_p2, "tmp_8_fu_469_p2");
    sc_trace(mVcdFile, j_3_fu_524_p2, "j_3_fu_524_p2");
    sc_trace(mVcdFile, j_3_reg_706, "j_3_reg_706");
    sc_trace(mVcdFile, tmp_21_fu_530_p2, "tmp_21_fu_530_p2");
    sc_trace(mVcdFile, sel_tmp4_fu_560_p2, "sel_tmp4_fu_560_p2");
    sc_trace(mVcdFile, angle_3_fu_571_p3, "angle_3_fu_571_p3");
    sc_trace(mVcdFile, angle_3_reg_728, "angle_3_reg_728");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st31_fsm_30, "ap_sig_cseq_ST_st31_fsm_30");
    sc_trace(mVcdFile, ap_sig_300, "ap_sig_300");
    sc_trace(mVcdFile, sigma_2_fu_620_p3, "sigma_2_fu_620_p3");
    sc_trace(mVcdFile, sigma_2_reg_733, "sigma_2_reg_733");
    sc_trace(mVcdFile, beta_assign_2_reg_739, "beta_assign_2_reg_739");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st47_fsm_46, "ap_sig_cseq_ST_st47_fsm_46");
    sc_trace(mVcdFile, ap_sig_310, "ap_sig_310");
    sc_trace(mVcdFile, beta_assign_3_fu_628_p3, "beta_assign_3_fu_628_p3");
    sc_trace(mVcdFile, beta_assign_3_reg_744, "beta_assign_3_reg_744");
    sc_trace(mVcdFile, s2_2_reg_749, "s2_2_reg_749");
    sc_trace(mVcdFile, c2_3_fu_634_p3, "c2_3_fu_634_p3");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st54_fsm_53, "ap_sig_cseq_ST_st54_fsm_53");
    sc_trace(mVcdFile, ap_sig_323, "ap_sig_323");
    sc_trace(mVcdFile, s2_3_fu_641_p3, "s2_3_fu_641_p3");
    sc_trace(mVcdFile, ch_load_reg_120, "ch_load_reg_120");
    sc_trace(mVcdFile, tmp_2_reg_132, "tmp_2_reg_132");
    sc_trace(mVcdFile, poweroftwo_reg_144, "poweroftwo_reg_144");
    sc_trace(mVcdFile, j1_reg_156, "j1_reg_156");
    sc_trace(mVcdFile, p_0_reg_165, "p_0_reg_165");
    sc_trace(mVcdFile, ch_load_2_reg_175, "ch_load_2_reg_175");
    sc_trace(mVcdFile, sh_load_reg_186, "sh_load_reg_186");
    sc_trace(mVcdFile, angle1_reg_197, "angle1_reg_197");
    sc_trace(mVcdFile, poweroftwo_1_reg_209, "poweroftwo_1_reg_209");
    sc_trace(mVcdFile, j_1_reg_220, "j_1_reg_220");
    sc_trace(mVcdFile, p_1_reg_232, "p_1_reg_232");
    sc_trace(mVcdFile, tmp_5_fu_408_p1, "tmp_5_fu_408_p1");
    sc_trace(mVcdFile, tmp_22_fu_566_p1, "tmp_22_fu_566_p1");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st59_fsm_58, "ap_sig_cseq_ST_st59_fsm_58");
    sc_trace(mVcdFile, ap_sig_362, "ap_sig_362");
    sc_trace(mVcdFile, grp_fu_243_p0, "grp_fu_243_p0");
    sc_trace(mVcdFile, grp_fu_243_p1, "grp_fu_243_p1");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st10_fsm_9, "ap_sig_cseq_ST_st10_fsm_9");
    sc_trace(mVcdFile, ap_sig_371, "ap_sig_371");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st19_fsm_18, "ap_sig_cseq_ST_st19_fsm_18");
    sc_trace(mVcdFile, ap_sig_378, "ap_sig_378");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st37_fsm_36, "ap_sig_cseq_ST_st37_fsm_36");
    sc_trace(mVcdFile, ap_sig_385, "ap_sig_385");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st43_fsm_42, "ap_sig_cseq_ST_st43_fsm_42");
    sc_trace(mVcdFile, ap_sig_392, "ap_sig_392");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st49_fsm_48, "ap_sig_cseq_ST_st49_fsm_48");
    sc_trace(mVcdFile, ap_sig_399, "ap_sig_399");
    sc_trace(mVcdFile, grp_fu_251_p1, "grp_fu_251_p1");
    sc_trace(mVcdFile, grp_fu_259_p0, "grp_fu_259_p0");
    sc_trace(mVcdFile, grp_fu_259_p1, "grp_fu_259_p1");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st4_fsm_3, "ap_sig_cseq_ST_st4_fsm_3");
    sc_trace(mVcdFile, ap_sig_416, "ap_sig_416");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st7_fsm_6, "ap_sig_cseq_ST_st7_fsm_6");
    sc_trace(mVcdFile, ap_sig_423, "ap_sig_423");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st13_fsm_12, "ap_sig_cseq_ST_st13_fsm_12");
    sc_trace(mVcdFile, ap_sig_431, "ap_sig_431");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st25_fsm_24, "ap_sig_cseq_ST_st25_fsm_24");
    sc_trace(mVcdFile, ap_sig_438, "ap_sig_438");
    sc_trace(mVcdFile, grp_fu_266_p0, "grp_fu_266_p0");
    sc_trace(mVcdFile, grp_fu_266_p1, "grp_fu_266_p1");
    sc_trace(mVcdFile, grp_fu_277_p0, "grp_fu_277_p0");
    sc_trace(mVcdFile, grp_fu_286_p0, "grp_fu_286_p0");
    sc_trace(mVcdFile, beta_to_int_fu_340_p1, "beta_to_int_fu_340_p1");
    sc_trace(mVcdFile, tmp_fu_344_p4, "tmp_fu_344_p4");
    sc_trace(mVcdFile, tmp_6_fu_354_p1, "tmp_6_fu_354_p1");
    sc_trace(mVcdFile, notrhs_fu_364_p2, "notrhs_fu_364_p2");
    sc_trace(mVcdFile, notlhs_fu_358_p2, "notlhs_fu_358_p2");
    sc_trace(mVcdFile, tmp_12_fu_370_p2, "tmp_12_fu_370_p2");
    sc_trace(mVcdFile, grp_fu_286_p2, "grp_fu_286_p2");
    sc_trace(mVcdFile, tmp_20_fu_376_p2, "tmp_20_fu_376_p2");
    sc_trace(mVcdFile, tmp_4_fu_402_p2, "tmp_4_fu_402_p2");
    sc_trace(mVcdFile, p_0_to_int_fu_419_p1, "p_0_to_int_fu_419_p1");
    sc_trace(mVcdFile, tmp_23_fu_423_p4, "tmp_23_fu_423_p4");
    sc_trace(mVcdFile, tmp_24_fu_433_p1, "tmp_24_fu_433_p1");
    sc_trace(mVcdFile, notrhs1_fu_443_p2, "notrhs1_fu_443_p2");
    sc_trace(mVcdFile, notlhs1_fu_437_p2, "notlhs1_fu_437_p2");
    sc_trace(mVcdFile, tmp_25_fu_449_p2, "tmp_25_fu_449_p2");
    sc_trace(mVcdFile, tmp_27_fu_455_p2, "tmp_27_fu_455_p2");
    sc_trace(mVcdFile, p_1_to_int_fu_474_p1, "p_1_to_int_fu_474_p1");
    sc_trace(mVcdFile, tmp_28_fu_478_p4, "tmp_28_fu_478_p4");
    sc_trace(mVcdFile, tmp_29_fu_488_p1, "tmp_29_fu_488_p1");
    sc_trace(mVcdFile, notrhs2_fu_498_p2, "notrhs2_fu_498_p2");
    sc_trace(mVcdFile, notlhs2_fu_492_p2, "notlhs2_fu_492_p2");
    sc_trace(mVcdFile, tmp_30_fu_504_p2, "tmp_30_fu_504_p2");
    sc_trace(mVcdFile, tmp_32_fu_510_p2, "tmp_32_fu_510_p2");
    sc_trace(mVcdFile, sel_tmp1_fu_542_p2, "sel_tmp1_fu_542_p2");
    sc_trace(mVcdFile, sel_tmp2_fu_548_p2, "sel_tmp2_fu_548_p2");
    sc_trace(mVcdFile, tmp1_fu_554_p2, "tmp1_fu_554_p2");
    sc_trace(mVcdFile, sel_tmp_fu_536_p2, "sel_tmp_fu_536_p2");
    sc_trace(mVcdFile, beta_assign_1_to_int_fu_578_p1, "beta_assign_1_to_int_fu_578_p1");
    sc_trace(mVcdFile, tmp_33_fu_582_p4, "tmp_33_fu_582_p4");
    sc_trace(mVcdFile, tmp_34_fu_592_p1, "tmp_34_fu_592_p1");
    sc_trace(mVcdFile, notrhs3_fu_602_p2, "notrhs3_fu_602_p2");
    sc_trace(mVcdFile, notlhs3_fu_596_p2, "notlhs3_fu_596_p2");
    sc_trace(mVcdFile, tmp_35_fu_608_p2, "tmp_35_fu_608_p2");
    sc_trace(mVcdFile, tmp_37_fu_614_p2, "tmp_37_fu_614_p2");
    sc_trace(mVcdFile, grp_fu_243_opcode, "grp_fu_243_opcode");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("coshsinh_cordic.hdltvin.dat");
    mHdltvoutHandle.open("coshsinh_cordic.hdltvout.dat");
}

coshsinh_cordic::~coshsinh_cordic() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete angles_neg_U;
    delete angles_pos_U;
    delete coshsinh_cordic_dadddsub_64ns_64ns_64_5_full_dsp_U0;
    delete coshsinh_cordic_dadd_64ns_64ns_64_5_full_dsp_U1;
    delete coshsinh_cordic_dmul_64ns_64ns_64_6_max_dsp_U2;
    delete coshsinh_cordic_dmul_64ns_64ns_64_6_max_dsp_U3;
    delete coshsinh_cordic_dmul_64ns_64ns_64_6_max_dsp_U4;
    delete coshsinh_cordic_dcmp_64ns_64ns_1_1_U5;
}

void coshsinh_cordic::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void coshsinh_cordic::thread_ap_var_for_const2() {
    ap_var_for_const2 = ap_const_lv64_0;
}

void coshsinh_cordic::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_lv64_3FE0000000000000;
}

void coshsinh_cordic::thread_ap_var_for_const3() {
    ap_var_for_const3 = ap_const_lv5_4;
}

void coshsinh_cordic::thread_ap_clk_no_reset_() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_3_fu_396_p2.read()))) {
        angle1_reg_197 = ap_const_lv64_3FE193DD97F62B6B;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st54_fsm_53.read())) {
        angle1_reg_197 = angle_3_reg_728.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_3_fu_396_p2.read()))) {
        ch_load_2_reg_175 = ch_load_reg_120.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st54_fsm_53.read())) {
        ch_load_2_reg_175 = c2_3_fu_634_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st23_fsm_22.read())) {
        ch_load_reg_120 = grp_fu_243_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        ch_load_reg_120 = ap_const_lv64_3FF0000000000000;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st23_fsm_22.read())) {
        j1_reg_156 = j_2_reg_676.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        j1_reg_156 = j_fu_390_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_3_fu_396_p2.read()))) {
        j_1_reg_220 = ap_const_lv32_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st54_fsm_53.read())) {
        j_1_reg_220 = j_3_reg_706.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st23_fsm_22.read())) {
        p_0_reg_165 = reg_294.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        p_0_reg_165 = beta.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_3_fu_396_p2.read()))) {
        p_1_reg_232 = p_0_reg_165.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st54_fsm_53.read())) {
        p_1_reg_232 = beta_assign_3_reg_744.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_3_fu_396_p2.read()))) {
        poweroftwo_1_reg_209 = poweroftwo_reg_144.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st54_fsm_53.read())) {
        poweroftwo_1_reg_209 = reg_335.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st23_fsm_22.read())) {
        poweroftwo_reg_144 = reg_302.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        poweroftwo_reg_144 = ap_const_lv64_3FB0000000000000;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_3_fu_396_p2.read()))) {
        sh_load_reg_186 = tmp_2_reg_132.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st54_fsm_53.read())) {
        sh_load_reg_186 = s2_3_fu_641_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st23_fsm_22.read())) {
        tmp_2_reg_132 = grp_fu_251_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        tmp_2_reg_132 = ap_const_lv64_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st31_fsm_30.read())) {
        angle_3_reg_728 = angle_3_fu_571_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        angle_reg_681 = angles_neg_q0.read();
        sigma_reg_686 = sigma_fu_461_p3.read();
    }
    if ((!esl_seteq<1,1,1>(sel_tmp4_reg_716.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st47_fsm_46.read()))) {
        beta_assign_2_reg_739 = grp_fu_243_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st48_fsm_47.read())) {
        beta_assign_3_reg_744 = beta_assign_3_fu_628_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
        factor_reg_691 = grp_fu_259_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_3_fu_396_p2.read()))) {
        j_2_reg_676 = j_2_fu_413_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st24_fsm_23.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_8_fu_469_p2.read()))) {
        j_3_reg_706 = j_3_fu_524_p2.read();
        sigma_1_reg_700 = sigma_1_fu_516_p3.read();
        tmp_21_reg_711 = tmp_21_fu_530_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st35_fsm_34.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st53_fsm_52.read()) && 
  !esl_seteq<1,1,1>(sel_tmp4_reg_716.read(), ap_const_lv1_0)))) {
        reg_294 = grp_fu_243_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st30_fsm_29.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st36_fsm_35.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st42_fsm_41.read()) || (!esl_seteq<1,1,1>(sel_tmp4_reg_716.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st48_fsm_47.read())))) {
        reg_302 = grp_fu_259_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read()))) {
        reg_310 = grp_fu_259_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st30_fsm_29.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st36_fsm_35.read()) || (!esl_seteq<1,1,1>(sel_tmp4_reg_716.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st48_fsm_47.read())) || esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read()) || (!esl_seteq<1,1,1>(sel_tmp4_reg_716.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st42_fsm_41.read())))) {
        reg_315 = grp_fu_266_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st23_fsm_22.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st41_fsm_40.read()))) {
        reg_321 = grp_fu_243_p2.read();
        reg_328 = grp_fu_251_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st42_fsm_41.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st30_fsm_29.read()) && 
  !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_21_reg_711.read())))) {
        reg_335 = grp_fu_277_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st53_fsm_52.read()) && !esl_seteq<1,1,1>(sel_tmp4_reg_716.read(), ap_const_lv1_0))) {
        s2_2_reg_749 = grp_fu_251_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st30_fsm_29.read())) {
        sel_tmp4_reg_716 = sel_tmp4_fu_560_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st36_fsm_35.read())) {
        sigma_2_reg_733 = sigma_2_fu_620_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        sign_factor_reg_657 = sign_factor_fu_382_p3.read();
    }
}

void coshsinh_cordic::thread_angle_3_fu_571_p3() {
    angle_3_fu_571_p3 = (!tmp_21_reg_711.read()[0].is_01())? sc_lv<64>(): ((tmp_21_reg_711.read()[0].to_bool())? reg_335.read(): angles_pos_q0.read());
}

void coshsinh_cordic::thread_angles_neg_address0() {
    angles_neg_address0 =  (sc_lv<4>) (tmp_5_fu_408_p1.read());
}

void coshsinh_cordic::thread_angles_neg_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        angles_neg_ce0 = ap_const_logic_1;
    } else {
        angles_neg_ce0 = ap_const_logic_0;
    }
}

void coshsinh_cordic::thread_angles_pos_address0() {
    angles_pos_address0 =  (sc_lv<6>) (tmp_22_fu_566_p1.read());
}

void coshsinh_cordic::thread_angles_pos_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st30_fsm_29.read())) {
        angles_pos_ce0 = ap_const_logic_1;
    } else {
        angles_pos_ce0 = ap_const_logic_0;
    }
}

void coshsinh_cordic::thread_ap_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st59_fsm_58.read())) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void coshsinh_cordic::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void coshsinh_cordic::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st59_fsm_58.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void coshsinh_cordic::thread_ap_sig_109() {
    ap_sig_109 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(5, 5));
}

void coshsinh_cordic::thread_ap_sig_116() {
    ap_sig_116 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(13, 13));
}

void coshsinh_cordic::thread_ap_sig_124() {
    ap_sig_124 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(34, 34));
}

void coshsinh_cordic::thread_ap_sig_132() {
    ap_sig_132 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(52, 52));
}

void coshsinh_cordic::thread_ap_sig_147() {
    ap_sig_147 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(7, 7));
}

void coshsinh_cordic::thread_ap_sig_154() {
    ap_sig_154 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(29, 29));
}

void coshsinh_cordic::thread_ap_sig_162() {
    ap_sig_162 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(35, 35));
}

void coshsinh_cordic::thread_ap_sig_170() {
    ap_sig_170 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(41, 41));
}

void coshsinh_cordic::thread_ap_sig_178() {
    ap_sig_178 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(47, 47));
}

void coshsinh_cordic::thread_ap_sig_188() {
    ap_sig_188 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(8, 8));
}

void coshsinh_cordic::thread_ap_sig_195() {
    ap_sig_195 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(17, 17));
}

void coshsinh_cordic::thread_ap_sig_211() {
    ap_sig_211 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(22, 22));
}

void coshsinh_cordic::thread_ap_sig_218() {
    ap_sig_218 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(40, 40));
}

void coshsinh_cordic::thread_ap_sig_248() {
    ap_sig_248 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void coshsinh_cordic::thread_ap_sig_262() {
    ap_sig_262 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void coshsinh_cordic::thread_ap_sig_272() {
    ap_sig_272 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(11, 11));
}

void coshsinh_cordic::thread_ap_sig_281() {
    ap_sig_281 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(23, 23));
}

void coshsinh_cordic::thread_ap_sig_300() {
    ap_sig_300 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(30, 30));
}

void coshsinh_cordic::thread_ap_sig_310() {
    ap_sig_310 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(46, 46));
}

void coshsinh_cordic::thread_ap_sig_323() {
    ap_sig_323 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(53, 53));
}

void coshsinh_cordic::thread_ap_sig_362() {
    ap_sig_362 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(58, 58));
}

void coshsinh_cordic::thread_ap_sig_371() {
    ap_sig_371 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(9, 9));
}

void coshsinh_cordic::thread_ap_sig_378() {
    ap_sig_378 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(18, 18));
}

void coshsinh_cordic::thread_ap_sig_385() {
    ap_sig_385 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(36, 36));
}

void coshsinh_cordic::thread_ap_sig_392() {
    ap_sig_392 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(42, 42));
}

void coshsinh_cordic::thread_ap_sig_399() {
    ap_sig_399 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(48, 48));
}

void coshsinh_cordic::thread_ap_sig_416() {
    ap_sig_416 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void coshsinh_cordic::thread_ap_sig_423() {
    ap_sig_423 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(6, 6));
}

void coshsinh_cordic::thread_ap_sig_431() {
    ap_sig_431 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(12, 12));
}

void coshsinh_cordic::thread_ap_sig_438() {
    ap_sig_438 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(24, 24));
}

void coshsinh_cordic::thread_ap_sig_74() {
    ap_sig_74 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void coshsinh_cordic::thread_ap_sig_cseq_ST_st10_fsm_9() {
    if (ap_sig_371.read()) {
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_0;
    }
}

void coshsinh_cordic::thread_ap_sig_cseq_ST_st12_fsm_11() {
    if (ap_sig_272.read()) {
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_0;
    }
}

void coshsinh_cordic::thread_ap_sig_cseq_ST_st13_fsm_12() {
    if (ap_sig_431.read()) {
        ap_sig_cseq_ST_st13_fsm_12 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st13_fsm_12 = ap_const_logic_0;
    }
}

void coshsinh_cordic::thread_ap_sig_cseq_ST_st14_fsm_13() {
    if (ap_sig_116.read()) {
        ap_sig_cseq_ST_st14_fsm_13 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st14_fsm_13 = ap_const_logic_0;
    }
}

void coshsinh_cordic::thread_ap_sig_cseq_ST_st18_fsm_17() {
    if (ap_sig_195.read()) {
        ap_sig_cseq_ST_st18_fsm_17 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st18_fsm_17 = ap_const_logic_0;
    }
}

void coshsinh_cordic::thread_ap_sig_cseq_ST_st19_fsm_18() {
    if (ap_sig_378.read()) {
        ap_sig_cseq_ST_st19_fsm_18 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st19_fsm_18 = ap_const_logic_0;
    }
}

void coshsinh_cordic::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_74.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void coshsinh_cordic::thread_ap_sig_cseq_ST_st23_fsm_22() {
    if (ap_sig_211.read()) {
        ap_sig_cseq_ST_st23_fsm_22 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st23_fsm_22 = ap_const_logic_0;
    }
}

void coshsinh_cordic::thread_ap_sig_cseq_ST_st24_fsm_23() {
    if (ap_sig_281.read()) {
        ap_sig_cseq_ST_st24_fsm_23 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st24_fsm_23 = ap_const_logic_0;
    }
}

void coshsinh_cordic::thread_ap_sig_cseq_ST_st25_fsm_24() {
    if (ap_sig_438.read()) {
        ap_sig_cseq_ST_st25_fsm_24 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st25_fsm_24 = ap_const_logic_0;
    }
}

void coshsinh_cordic::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_248.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void coshsinh_cordic::thread_ap_sig_cseq_ST_st30_fsm_29() {
    if (ap_sig_154.read()) {
        ap_sig_cseq_ST_st30_fsm_29 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st30_fsm_29 = ap_const_logic_0;
    }
}

void coshsinh_cordic::thread_ap_sig_cseq_ST_st31_fsm_30() {
    if (ap_sig_300.read()) {
        ap_sig_cseq_ST_st31_fsm_30 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st31_fsm_30 = ap_const_logic_0;
    }
}

void coshsinh_cordic::thread_ap_sig_cseq_ST_st35_fsm_34() {
    if (ap_sig_124.read()) {
        ap_sig_cseq_ST_st35_fsm_34 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st35_fsm_34 = ap_const_logic_0;
    }
}

void coshsinh_cordic::thread_ap_sig_cseq_ST_st36_fsm_35() {
    if (ap_sig_162.read()) {
        ap_sig_cseq_ST_st36_fsm_35 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st36_fsm_35 = ap_const_logic_0;
    }
}

void coshsinh_cordic::thread_ap_sig_cseq_ST_st37_fsm_36() {
    if (ap_sig_385.read()) {
        ap_sig_cseq_ST_st37_fsm_36 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st37_fsm_36 = ap_const_logic_0;
    }
}

void coshsinh_cordic::thread_ap_sig_cseq_ST_st3_fsm_2() {
    if (ap_sig_262.read()) {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    }
}

void coshsinh_cordic::thread_ap_sig_cseq_ST_st41_fsm_40() {
    if (ap_sig_218.read()) {
        ap_sig_cseq_ST_st41_fsm_40 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st41_fsm_40 = ap_const_logic_0;
    }
}

void coshsinh_cordic::thread_ap_sig_cseq_ST_st42_fsm_41() {
    if (ap_sig_170.read()) {
        ap_sig_cseq_ST_st42_fsm_41 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st42_fsm_41 = ap_const_logic_0;
    }
}

void coshsinh_cordic::thread_ap_sig_cseq_ST_st43_fsm_42() {
    if (ap_sig_392.read()) {
        ap_sig_cseq_ST_st43_fsm_42 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st43_fsm_42 = ap_const_logic_0;
    }
}

void coshsinh_cordic::thread_ap_sig_cseq_ST_st47_fsm_46() {
    if (ap_sig_310.read()) {
        ap_sig_cseq_ST_st47_fsm_46 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st47_fsm_46 = ap_const_logic_0;
    }
}

void coshsinh_cordic::thread_ap_sig_cseq_ST_st48_fsm_47() {
    if (ap_sig_178.read()) {
        ap_sig_cseq_ST_st48_fsm_47 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st48_fsm_47 = ap_const_logic_0;
    }
}

void coshsinh_cordic::thread_ap_sig_cseq_ST_st49_fsm_48() {
    if (ap_sig_399.read()) {
        ap_sig_cseq_ST_st49_fsm_48 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st49_fsm_48 = ap_const_logic_0;
    }
}

void coshsinh_cordic::thread_ap_sig_cseq_ST_st4_fsm_3() {
    if (ap_sig_416.read()) {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    }
}

void coshsinh_cordic::thread_ap_sig_cseq_ST_st53_fsm_52() {
    if (ap_sig_132.read()) {
        ap_sig_cseq_ST_st53_fsm_52 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st53_fsm_52 = ap_const_logic_0;
    }
}

void coshsinh_cordic::thread_ap_sig_cseq_ST_st54_fsm_53() {
    if (ap_sig_323.read()) {
        ap_sig_cseq_ST_st54_fsm_53 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st54_fsm_53 = ap_const_logic_0;
    }
}

void coshsinh_cordic::thread_ap_sig_cseq_ST_st59_fsm_58() {
    if (ap_sig_362.read()) {
        ap_sig_cseq_ST_st59_fsm_58 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st59_fsm_58 = ap_const_logic_0;
    }
}

void coshsinh_cordic::thread_ap_sig_cseq_ST_st6_fsm_5() {
    if (ap_sig_109.read()) {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_0;
    }
}

void coshsinh_cordic::thread_ap_sig_cseq_ST_st7_fsm_6() {
    if (ap_sig_423.read()) {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_0;
    }
}

void coshsinh_cordic::thread_ap_sig_cseq_ST_st8_fsm_7() {
    if (ap_sig_147.read()) {
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_0;
    }
}

void coshsinh_cordic::thread_ap_sig_cseq_ST_st9_fsm_8() {
    if (ap_sig_188.read()) {
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_0;
    }
}

void coshsinh_cordic::thread_beta_assign_1_to_int_fu_578_p1() {
    beta_assign_1_to_int_fu_578_p1 = reg_294.read();
}

void coshsinh_cordic::thread_beta_assign_3_fu_628_p3() {
    beta_assign_3_fu_628_p3 = (!sel_tmp4_reg_716.read()[0].is_01())? sc_lv<64>(): ((sel_tmp4_reg_716.read()[0].to_bool())? beta_assign_2_reg_739.read(): reg_294.read());
}

void coshsinh_cordic::thread_beta_to_int_fu_340_p1() {
    beta_to_int_fu_340_p1 = beta.read();
}

void coshsinh_cordic::thread_c2_3_fu_634_p3() {
    c2_3_fu_634_p3 = (!sel_tmp4_reg_716.read()[0].is_01())? sc_lv<64>(): ((sel_tmp4_reg_716.read()[0].to_bool())? reg_294.read(): reg_321.read());
}

void coshsinh_cordic::thread_ch() {
    ch = grp_fu_259_p2.read();
}

void coshsinh_cordic::thread_ch_ap_vld() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st59_fsm_58.read())) {
        ch_ap_vld = ap_const_logic_1;
    } else {
        ch_ap_vld = ap_const_logic_0;
    }
}

void coshsinh_cordic::thread_grp_fu_243_opcode() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_3_fu_396_p2.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st31_fsm_30.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read()) || 
         (!esl_seteq<1,1,1>(sel_tmp4_reg_716.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st43_fsm_42.read())))) {
        grp_fu_243_opcode = ap_const_lv2_1;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st19_fsm_18.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st37_fsm_36.read()) || 
                (!esl_seteq<1,1,1>(sel_tmp4_reg_716.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st49_fsm_48.read())))) {
        grp_fu_243_opcode = ap_const_lv2_0;
    } else {
        grp_fu_243_opcode = "XX";
    }
}

void coshsinh_cordic::thread_grp_fu_243_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st49_fsm_48.read())) {
        grp_fu_243_p0 = reg_321.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st43_fsm_42.read())) {
        grp_fu_243_p0 = reg_294.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st37_fsm_36.read())) {
        grp_fu_243_p0 = ch_load_2_reg_175.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st31_fsm_30.read())) {
        grp_fu_243_p0 = p_1_reg_232.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st19_fsm_18.read())) {
        grp_fu_243_p0 = ch_load_reg_120.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())) {
        grp_fu_243_p0 = p_0_reg_165.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        grp_fu_243_p0 = ap_const_lv64_3FF0000000000000;
    } else {
        grp_fu_243_p0 =  (sc_lv<64>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void coshsinh_cordic::thread_grp_fu_243_p1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st37_fsm_36.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st49_fsm_48.read()))) {
        grp_fu_243_p1 = reg_302.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st31_fsm_30.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st43_fsm_42.read()))) {
        grp_fu_243_p1 = reg_315.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st19_fsm_18.read()))) {
        grp_fu_243_p1 = reg_310.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        grp_fu_243_p1 = poweroftwo_reg_144.read();
    } else {
        grp_fu_243_p1 =  (sc_lv<64>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void coshsinh_cordic::thread_grp_fu_251_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st49_fsm_48.read())) {
        grp_fu_251_p1 = reg_328.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st37_fsm_36.read())) {
        grp_fu_251_p1 = sh_load_reg_186.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st19_fsm_18.read())) {
        grp_fu_251_p1 = tmp_2_reg_132.read();
    } else {
        grp_fu_251_p1 =  (sc_lv<64>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void coshsinh_cordic::thread_grp_fu_259_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st37_fsm_36.read())) {
        grp_fu_259_p0 = sigma_2_reg_733.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st31_fsm_30.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st43_fsm_42.read()))) {
        grp_fu_259_p0 = reg_302.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st25_fsm_24.read())) {
        grp_fu_259_p0 = sigma_1_reg_700.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st24_fsm_23.read())) {
        grp_fu_259_p0 = sign_factor_reg_657.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read())) {
        grp_fu_259_p0 = factor_reg_691.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()))) {
        grp_fu_259_p0 = sigma_reg_686.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        grp_fu_259_p0 = poweroftwo_reg_144.read();
    } else {
        grp_fu_259_p0 =  (sc_lv<64>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void coshsinh_cordic::thread_grp_fu_259_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st43_fsm_42.read())) {
        grp_fu_259_p1 = reg_328.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st31_fsm_30.read())) {
        grp_fu_259_p1 = sh_load_reg_186.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st37_fsm_36.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st25_fsm_24.read()))) {
        grp_fu_259_p1 = poweroftwo_1_reg_209.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st24_fsm_23.read())) {
        grp_fu_259_p1 = ch_load_2_reg_175.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read())) {
        grp_fu_259_p1 = tmp_2_reg_132.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
        grp_fu_259_p1 = reg_294.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        grp_fu_259_p1 = angle_reg_681.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        grp_fu_259_p1 = ap_const_lv64_4000000000000000;
    } else {
        grp_fu_259_p1 =  (sc_lv<64>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void coshsinh_cordic::thread_grp_fu_266_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st37_fsm_36.read())) {
        grp_fu_266_p0 = sigma_2_reg_733.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st31_fsm_30.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st43_fsm_42.read()))) {
        grp_fu_266_p0 = reg_302.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st25_fsm_24.read())) {
        grp_fu_266_p0 = sigma_1_reg_700.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st24_fsm_23.read())) {
        grp_fu_266_p0 = sign_factor_reg_657.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read())) {
        grp_fu_266_p0 = factor_reg_691.read();
    } else {
        grp_fu_266_p0 =  (sc_lv<64>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void coshsinh_cordic::thread_grp_fu_266_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st43_fsm_42.read())) {
        grp_fu_266_p1 = reg_321.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st31_fsm_30.read())) {
        grp_fu_266_p1 = ch_load_2_reg_175.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st37_fsm_36.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st25_fsm_24.read()))) {
        grp_fu_266_p1 = angle1_reg_197.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st24_fsm_23.read())) {
        grp_fu_266_p1 = sh_load_reg_186.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read())) {
        grp_fu_266_p1 = ch_load_reg_120.read();
    } else {
        grp_fu_266_p1 =  (sc_lv<64>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void coshsinh_cordic::thread_grp_fu_277_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st37_fsm_36.read())) {
        grp_fu_277_p0 = poweroftwo_1_reg_209.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st25_fsm_24.read())) {
        grp_fu_277_p0 = angle1_reg_197.read();
    } else {
        grp_fu_277_p0 =  (sc_lv<64>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void coshsinh_cordic::thread_grp_fu_286_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st36_fsm_35.read())) {
        grp_fu_286_p0 = reg_294.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st24_fsm_23.read())) {
        grp_fu_286_p0 = p_1_reg_232.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        grp_fu_286_p0 = p_0_reg_165.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read())) {
        grp_fu_286_p0 = beta.read();
    } else {
        grp_fu_286_p0 =  (sc_lv<64>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void coshsinh_cordic::thread_j_2_fu_413_p2() {
    j_2_fu_413_p2 = (!ap_const_lv32_1.is_01() || !j1_reg_156.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_1) + sc_biguint<32>(j1_reg_156.read()));
}

void coshsinh_cordic::thread_j_3_fu_524_p2() {
    j_3_fu_524_p2 = (!ap_const_lv32_1.is_01() || !j_1_reg_220.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_1) + sc_biguint<32>(j_1_reg_220.read()));
}

void coshsinh_cordic::thread_j_fu_390_p2() {
    j_fu_390_p2 = (!ap_const_lv32_0.is_01() || !m.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_0) - sc_biguint<32>(m.read()));
}

void coshsinh_cordic::thread_notlhs1_fu_437_p2() {
    notlhs1_fu_437_p2 = (!tmp_23_fu_423_p4.read().is_01() || !ap_const_lv11_7FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_23_fu_423_p4.read() != ap_const_lv11_7FF);
}

void coshsinh_cordic::thread_notlhs2_fu_492_p2() {
    notlhs2_fu_492_p2 = (!tmp_28_fu_478_p4.read().is_01() || !ap_const_lv11_7FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_28_fu_478_p4.read() != ap_const_lv11_7FF);
}

void coshsinh_cordic::thread_notlhs3_fu_596_p2() {
    notlhs3_fu_596_p2 = (!tmp_33_fu_582_p4.read().is_01() || !ap_const_lv11_7FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_33_fu_582_p4.read() != ap_const_lv11_7FF);
}

void coshsinh_cordic::thread_notlhs_fu_358_p2() {
    notlhs_fu_358_p2 = (!tmp_fu_344_p4.read().is_01() || !ap_const_lv11_7FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_fu_344_p4.read() != ap_const_lv11_7FF);
}

void coshsinh_cordic::thread_notrhs1_fu_443_p2() {
    notrhs1_fu_443_p2 = (!tmp_24_fu_433_p1.read().is_01() || !ap_const_lv52_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_24_fu_433_p1.read() == ap_const_lv52_0);
}

void coshsinh_cordic::thread_notrhs2_fu_498_p2() {
    notrhs2_fu_498_p2 = (!tmp_29_fu_488_p1.read().is_01() || !ap_const_lv52_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_29_fu_488_p1.read() == ap_const_lv52_0);
}

void coshsinh_cordic::thread_notrhs3_fu_602_p2() {
    notrhs3_fu_602_p2 = (!tmp_34_fu_592_p1.read().is_01() || !ap_const_lv52_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_34_fu_592_p1.read() == ap_const_lv52_0);
}

void coshsinh_cordic::thread_notrhs_fu_364_p2() {
    notrhs_fu_364_p2 = (!tmp_6_fu_354_p1.read().is_01() || !ap_const_lv52_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_6_fu_354_p1.read() == ap_const_lv52_0);
}

void coshsinh_cordic::thread_p_0_to_int_fu_419_p1() {
    p_0_to_int_fu_419_p1 = p_0_reg_165.read();
}

void coshsinh_cordic::thread_p_1_to_int_fu_474_p1() {
    p_1_to_int_fu_474_p1 = p_1_reg_232.read();
}

void coshsinh_cordic::thread_s2_3_fu_641_p3() {
    s2_3_fu_641_p3 = (!sel_tmp4_reg_716.read()[0].is_01())? sc_lv<64>(): ((sel_tmp4_reg_716.read()[0].to_bool())? s2_2_reg_749.read(): reg_328.read());
}

void coshsinh_cordic::thread_sel_tmp1_fu_542_p2() {
    sel_tmp1_fu_542_p2 = (!j_1_reg_220.read().is_01() || !ap_const_lv32_D.is_01())? sc_lv<1>(): sc_lv<1>(j_1_reg_220.read() == ap_const_lv32_D);
}

void coshsinh_cordic::thread_sel_tmp2_fu_548_p2() {
    sel_tmp2_fu_548_p2 = (!j_1_reg_220.read().is_01() || !ap_const_lv32_4.is_01())? sc_lv<1>(): sc_lv<1>(j_1_reg_220.read() == ap_const_lv32_4);
}

void coshsinh_cordic::thread_sel_tmp4_fu_560_p2() {
    sel_tmp4_fu_560_p2 = (tmp1_fu_554_p2.read() | sel_tmp_fu_536_p2.read());
}

void coshsinh_cordic::thread_sel_tmp_fu_536_p2() {
    sel_tmp_fu_536_p2 = (!j_1_reg_220.read().is_01() || !ap_const_lv32_28.is_01())? sc_lv<1>(): sc_lv<1>(j_1_reg_220.read() == ap_const_lv32_28);
}

void coshsinh_cordic::thread_sh() {
    sh = grp_fu_266_p2.read();
}

void coshsinh_cordic::thread_sh_ap_vld() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st59_fsm_58.read())) {
        sh_ap_vld = ap_const_logic_1;
    } else {
        sh_ap_vld = ap_const_logic_0;
    }
}

void coshsinh_cordic::thread_sigma_1_fu_516_p3() {
    sigma_1_fu_516_p3 = (!tmp_32_fu_510_p2.read()[0].is_01())? sc_lv<64>(): ((tmp_32_fu_510_p2.read()[0].to_bool())? ap_const_lv64_BFF0000000000000: ap_const_lv64_3FF0000000000000);
}

void coshsinh_cordic::thread_sigma_2_fu_620_p3() {
    sigma_2_fu_620_p3 = (!tmp_37_fu_614_p2.read()[0].is_01())? sc_lv<64>(): ((tmp_37_fu_614_p2.read()[0].to_bool())? ap_const_lv64_BFF0000000000000: ap_const_lv64_3FF0000000000000);
}

void coshsinh_cordic::thread_sigma_fu_461_p3() {
    sigma_fu_461_p3 = (!tmp_27_fu_455_p2.read()[0].is_01())? sc_lv<64>(): ((tmp_27_fu_455_p2.read()[0].to_bool())? ap_const_lv64_BFF0000000000000: ap_const_lv64_3FF0000000000000);
}

void coshsinh_cordic::thread_sign_factor_fu_382_p3() {
    sign_factor_fu_382_p3 = (!tmp_20_fu_376_p2.read()[0].is_01())? sc_lv<64>(): ((tmp_20_fu_376_p2.read()[0].to_bool())? ap_const_lv64_BFF0000000000000: ap_const_lv64_3FF0000000000000);
}

void coshsinh_cordic::thread_tmp1_fu_554_p2() {
    tmp1_fu_554_p2 = (sel_tmp1_fu_542_p2.read() | sel_tmp2_fu_548_p2.read());
}

void coshsinh_cordic::thread_tmp_12_fu_370_p2() {
    tmp_12_fu_370_p2 = (notrhs_fu_364_p2.read() | notlhs_fu_358_p2.read());
}

void coshsinh_cordic::thread_tmp_20_fu_376_p2() {
    tmp_20_fu_376_p2 = (tmp_12_fu_370_p2.read() & grp_fu_286_p2.read());
}

void coshsinh_cordic::thread_tmp_21_fu_530_p2() {
    tmp_21_fu_530_p2 = (!j_3_fu_524_p2.read().is_01() || !ap_const_lv32_3C.is_01())? sc_lv<1>(): (sc_bigint<32>(j_3_fu_524_p2.read()) > sc_bigint<32>(ap_const_lv32_3C));
}

void coshsinh_cordic::thread_tmp_22_fu_566_p1() {
    tmp_22_fu_566_p1 = esl_zext<64,32>(j_1_reg_220.read());
}

void coshsinh_cordic::thread_tmp_23_fu_423_p4() {
    tmp_23_fu_423_p4 = p_0_to_int_fu_419_p1.read().range(62, 52);
}

void coshsinh_cordic::thread_tmp_24_fu_433_p1() {
    tmp_24_fu_433_p1 = p_0_to_int_fu_419_p1.read().range(52-1, 0);
}

void coshsinh_cordic::thread_tmp_25_fu_449_p2() {
    tmp_25_fu_449_p2 = (notrhs1_fu_443_p2.read() | notlhs1_fu_437_p2.read());
}

void coshsinh_cordic::thread_tmp_27_fu_455_p2() {
    tmp_27_fu_455_p2 = (tmp_25_fu_449_p2.read() & grp_fu_286_p2.read());
}

void coshsinh_cordic::thread_tmp_28_fu_478_p4() {
    tmp_28_fu_478_p4 = p_1_to_int_fu_474_p1.read().range(62, 52);
}

void coshsinh_cordic::thread_tmp_29_fu_488_p1() {
    tmp_29_fu_488_p1 = p_1_to_int_fu_474_p1.read().range(52-1, 0);
}

void coshsinh_cordic::thread_tmp_30_fu_504_p2() {
    tmp_30_fu_504_p2 = (notrhs2_fu_498_p2.read() | notlhs2_fu_492_p2.read());
}

void coshsinh_cordic::thread_tmp_32_fu_510_p2() {
    tmp_32_fu_510_p2 = (tmp_30_fu_504_p2.read() & grp_fu_286_p2.read());
}

void coshsinh_cordic::thread_tmp_33_fu_582_p4() {
    tmp_33_fu_582_p4 = beta_assign_1_to_int_fu_578_p1.read().range(62, 52);
}

void coshsinh_cordic::thread_tmp_34_fu_592_p1() {
    tmp_34_fu_592_p1 = beta_assign_1_to_int_fu_578_p1.read().range(52-1, 0);
}

void coshsinh_cordic::thread_tmp_35_fu_608_p2() {
    tmp_35_fu_608_p2 = (notrhs3_fu_602_p2.read() | notlhs3_fu_596_p2.read());
}

void coshsinh_cordic::thread_tmp_37_fu_614_p2() {
    tmp_37_fu_614_p2 = (tmp_35_fu_608_p2.read() & grp_fu_286_p2.read());
}

void coshsinh_cordic::thread_tmp_3_fu_396_p2() {
    tmp_3_fu_396_p2 = (!j1_reg_156.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<1>(): (sc_bigint<32>(j1_reg_156.read()) < sc_bigint<32>(ap_const_lv32_1));
}

void coshsinh_cordic::thread_tmp_4_fu_402_p2() {
    tmp_4_fu_402_p2 = (!ap_const_lv32_0.is_01() || !j1_reg_156.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_0) - sc_biguint<32>(j1_reg_156.read()));
}

void coshsinh_cordic::thread_tmp_5_fu_408_p1() {
    tmp_5_fu_408_p1 = esl_sext<64,32>(tmp_4_fu_402_p2.read());
}

void coshsinh_cordic::thread_tmp_6_fu_354_p1() {
    tmp_6_fu_354_p1 = beta_to_int_fu_340_p1.read().range(52-1, 0);
}

void coshsinh_cordic::thread_tmp_8_fu_469_p2() {
    tmp_8_fu_469_p2 = (!j_1_reg_220.read().is_01() || !n.read().is_01())? sc_lv<1>(): (sc_bigint<32>(j_1_reg_220.read()) > sc_bigint<32>(n.read()));
}

void coshsinh_cordic::thread_tmp_fu_344_p4() {
    tmp_fu_344_p4 = beta_to_int_fu_340_p1.read().range(62, 52);
}

void coshsinh_cordic::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if (esl_seteq<1,1,1>(ap_const_lv1_0, tmp_3_fu_396_p2.read())) {
                ap_NS_fsm = ap_ST_st24_fsm_23;
            } else {
                ap_NS_fsm = ap_ST_st3_fsm_2;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_st4_fsm_3;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_st5_fsm_4;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_st6_fsm_5;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_st7_fsm_6;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_st8_fsm_7;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_st9_fsm_8;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_st10_fsm_9;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_st11_fsm_10;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_st12_fsm_11;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_st13_fsm_12;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_st14_fsm_13;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_st15_fsm_14;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_st16_fsm_15;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_st17_fsm_16;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_st18_fsm_17;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_st19_fsm_18;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_st20_fsm_19;
            break;
        case 524288 : 
            ap_NS_fsm = ap_ST_st21_fsm_20;
            break;
        case 1048576 : 
            ap_NS_fsm = ap_ST_st22_fsm_21;
            break;
        case 2097152 : 
            ap_NS_fsm = ap_ST_st23_fsm_22;
            break;
        case 4194304 : 
            ap_NS_fsm = ap_ST_st2_fsm_1;
            break;
        case 8388608 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, tmp_8_fu_469_p2.read())) {
                ap_NS_fsm = ap_ST_st55_fsm_54;
            } else {
                ap_NS_fsm = ap_ST_st25_fsm_24;
            }
            break;
        case 16777216 : 
            ap_NS_fsm = ap_ST_st26_fsm_25;
            break;
        case 33554432 : 
            ap_NS_fsm = ap_ST_st27_fsm_26;
            break;
        case 67108864 : 
            ap_NS_fsm = ap_ST_st28_fsm_27;
            break;
        case 134217728 : 
            ap_NS_fsm = ap_ST_st29_fsm_28;
            break;
        case 268435456 : 
            ap_NS_fsm = ap_ST_st30_fsm_29;
            break;
        case 536870912 : 
            ap_NS_fsm = ap_ST_st31_fsm_30;
            break;
        case 1073741824 : 
            ap_NS_fsm = ap_ST_st32_fsm_31;
            break;
        case 2147483648 : 
            ap_NS_fsm = ap_ST_st33_fsm_32;
            break;
        case 4294967296 : 
            ap_NS_fsm = ap_ST_st34_fsm_33;
            break;
        case 8589934592 : 
            ap_NS_fsm = ap_ST_st35_fsm_34;
            break;
        case 17179869184 : 
            ap_NS_fsm = ap_ST_st36_fsm_35;
            break;
        case 34359738368 : 
            ap_NS_fsm = ap_ST_st37_fsm_36;
            break;
        case 68719476736 : 
            ap_NS_fsm = ap_ST_st38_fsm_37;
            break;
        case 137438953472 : 
            ap_NS_fsm = ap_ST_st39_fsm_38;
            break;
        case 274877906944 : 
            ap_NS_fsm = ap_ST_st40_fsm_39;
            break;
        case 549755813888 : 
            ap_NS_fsm = ap_ST_st41_fsm_40;
            break;
        case 1099511627776 : 
            ap_NS_fsm = ap_ST_st42_fsm_41;
            break;
        case 2199023255552 : 
            ap_NS_fsm = ap_ST_st43_fsm_42;
            break;
        case 4398046511104 : 
            ap_NS_fsm = ap_ST_st44_fsm_43;
            break;
        case 8796093022208 : 
            ap_NS_fsm = ap_ST_st45_fsm_44;
            break;
        case 17592186044416 : 
            ap_NS_fsm = ap_ST_st46_fsm_45;
            break;
        case 35184372088832 : 
            ap_NS_fsm = ap_ST_st47_fsm_46;
            break;
        case 70368744177664 : 
            ap_NS_fsm = ap_ST_st48_fsm_47;
            break;
        case 140737488355328 : 
            ap_NS_fsm = ap_ST_st49_fsm_48;
            break;
        case 281474976710656 : 
            ap_NS_fsm = ap_ST_st50_fsm_49;
            break;
        case 562949953421312 : 
            ap_NS_fsm = ap_ST_st51_fsm_50;
            break;
        case 1125899906842624 : 
            ap_NS_fsm = ap_ST_st52_fsm_51;
            break;
        case 2251799813685248 : 
            ap_NS_fsm = ap_ST_st53_fsm_52;
            break;
        case 4503599627370496 : 
            ap_NS_fsm = ap_ST_st54_fsm_53;
            break;
        case 9007199254740992 : 
            ap_NS_fsm = ap_ST_st24_fsm_23;
            break;
        case 18014398509481984 : 
            ap_NS_fsm = ap_ST_st56_fsm_55;
            break;
        case 36028797018963968 : 
            ap_NS_fsm = ap_ST_st57_fsm_56;
            break;
        case 72057594037927936 : 
            ap_NS_fsm = ap_ST_st58_fsm_57;
            break;
        case 144115188075855872 : 
            ap_NS_fsm = ap_ST_st59_fsm_58;
            break;
        case 288230376151711744 : 
            ap_NS_fsm = ap_ST_st1_fsm_0;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<59>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
            break;
    }
}

void coshsinh_cordic::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"beta\" :  \"" << beta.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m\" :  \"" << m.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"n\" :  \"" << n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ch\" :  \"" << ch.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ch_ap_vld\" :  \"" << ch_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"sh\" :  \"" << sh.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"sh_ap_vld\" :  \"" << sh_ap_vld.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

